== Conformance

The OGC Cartographic Symbology - Part 2 - Model extension for graphical shapes and transmformations defines multiple requirements classes and their associated conformance classes, extending the core model
defined in Part 1. The encodings defined in Part 1 can be also used to encode the capabilities defined in this extension.

The standardization target for all conformance classes are both Encodings and Rendering engines.

The conformance of all Rendering engines with all conformance classes is with the conceptual model that will result in the expected visual output.
Conformance at the logical level implies conformance at the conceptual level as well.
An Encoding conforms to the logical model if a Style can be encoded using the classes and property names defined in this Standard with only a simple consistent set of rules mapping them to the encoding.
An Encoding can conform to the conceptual model of any conformance class either partially (if it can only preserve some of the information) or fully (if it losslessly preserves all information).

The goal is to allow different encodings to have equivalent content and semantics so that they can be interoperable, by establishing a clear mapping from an encoding
to the logical and/or conceptual model defined in this Standard. The granularity of conformance classes provides a mechanism to clearly indicate which portrayal capabilities
are interoperable with other encodings or rendering engines implementing this Standard.
Most Encodings and Rendering engines are expected to easily conform to the requirements classes for basic portrayal.

Requirements and conformance test URIs defined in this document are relative to http://www.opengis.net/spec/symbology-2/1.0.

=== Requirements classes for common portrayal capabilities

*<<rc-gradients,Requirements Class "Gradient Fills">>* (http://www.opengis.net/spec/symbology-1/1.0/req/gradients)

The Gradient Fills Requirements Class specifies requirements for defining fils using gradients.

*<<rc-shapegraphics,Requirements Class "Shape Graphics">>* (http://www.opengis.net/spec/symbology-1/1.0/req/shapegraphics)

The Shape Graphics Requirements Class specifies requirements for defining geometric shapes which can be used for markers, labels (with Basic Labeling),
or as patterns for stroke (with Pattern Strokes) or for fills (with Pattern Fills).

*<<rc-vector-geometry,Requirements Class "Vector Geometry Properties">>* (http://www.opengis.net/spec/symbology-1/1.0/req/geometryproperties)

The Vector Geometry Properties Requirements Class specifies requirements for using system identifiers to query the area and perimeter of vector geometry.

=== Requirements classes for advanced stroke and fills

*<<rc-joinscaps,Requirements Class "Joins and Caps">>* (http://www.opengis.net/spec/symbology-1/1.0/req/joinscaps)

The Joins and Caps Requirements Class specifies requirements for defining  a particular type of join and/or cap on strokes.

*<<rc-patternstrokes,Requirements Class "Pattern Strokes">>* (http://www.opengis.net/spec/symbology-1/1.0/req/patternstrokes)

The Pattern Strokes Requirements Class specifies requirements for defining patern strokes using Graphics.

*<<rc-patternfills,Requirements Class "Pattern Fills">>* (http://www.opengis.net/spec/symbology-1/1.0/req/patternfills)

The Pattern Strokes Requirements Class specifies requirements for defining patern fills using Graphics.

=== Requirements classes for additional portrayal capabilities

*<<rc-shapeoutlines,Requirements Class "Shape Outlines">>* (http://www.opengis.net/spec/symbology-1/1.0/req/shapeoutlines)

The Shape Outlines Requirements Class specifies requirements for displaying shapes with outlines so that they stand out on any background.

*<<rc-transforms,Requirements Class "MultiGraphics and Transforms">>* (http://www.opengis.net/spec/symbology-1/1.0/req/transforms)

The MultiGraphics and Transforms Requirements Class specifies requirements for building vector graphic hierarchy, including support for arbitrary transforms (translation, rotation and scaling).

*<<rc-imageoutlines,Requirements Class "Image Outlines">>* (http://www.opengis.net/spec/symbology-1/1.0/req/imageoutlines)

The Image Outlines Requirements Class specifies requirements for displaying images with outlines so that they stand out on any background.

*<<rc-threedim,Requirements Class "3D Models and Transforms">>* (http://www.opengis.net/spec/symbology-1/1.0/req/threedim)

The 3D Models and Transforms Requirements Class specifies requirements for defining 3D model Graphics and 3D transformations.

=== Declaration of conformance

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document conformance to the respective conformance class is declared using the URIs listed
in <<table_conformance_urls>>. A rendering engine accessible as an Web API can declare conformance to this Standard in its Conformance Declaration response.

The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the
OGC Compliance Testing Policies and Procedures (https://docs.ogc.org/pol/08-134r11.html[OGC 08-134r11]) and the https://www.ogc.org/compliance[OGC Compliance Testing website].

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

Full conformance at the conceptual level but not at the logical level, which can losslessly preserve all information of the conceptual model defined in a particular requirements class
but necessitates defining a custom mapping and cannot be automated from a simple consistent set of encoding rules, is declared by appending `-concept` to the conformance URI.

Partial conformance at the conceptual level which can preserve some but not all information of the conceptual model defined in a particular requirements class
is declared by appending `-partial-concept` to the conformance URI.

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Conformance class                                               |URI
|<<rc-shapegraphics,Shape Graphics>>                              |http://www.opengis.net/spec/symbology-1/1.0/conf/shapegraphics
|<<rc-shapeoutlines,Shape Outlines>>                              |http://www.opengis.net/spec/symbology-1/1.0/conf/shapeoutlines
|<<rc-transforms,Multi Graphics and Transforms>>                  |http://www.opengis.net/spec/symbology-1/1.0/conf/transforms
|<<rc-joins-caps,Joins and Caps>>                                  |http://www.opengis.net/spec/symbology-1/1.0/conf/joinscaps
|<<rc-pattern-strokes,Pattern Strokes>>                            |http://www.opengis.net/spec/symbology-1/1.0/conf/patternstrokes
|<<rc-pattern-fills,Pattern Fills>>                                |http://www.opengis.net/spec/symbology-1/1.0/conf/patternfills
|<<rc-gradients,Gradients Fills>>                                |http://www.opengis.net/spec/symbology-1/1.0/conf/gradients
|<<rc-threedim,3D Graphics, Models and Transforms>>               |http://www.opengis.net/spec/symbology-1/1.0/conf/threedim
|<<rc-image-outlines,Image Outlines>>                              |http://www.opengis.net/spec/symbology-1/1.0/conf/imageoutlines
|<<rc-geometry-properties,Vector Geometry Properties>>             |http://www.opengis.net/spec/symbology-1/1.0/conf/geometryproperties
|===
