
.Preface


*OGC Declaration*

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium Inc. shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[abstract]
== Abstract

This document proposes a set of concrete extensions of the Symbology
Conceptual Core Model standard to control how 2D features data (eg.
vector layer) are rendered.


[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
|Name |Affiliation |OGC member
|Erwan Bocher |CNRS | Yes
|Ertz Olivier |HEIG-VD | Yes
|Matt Sorenson |Strategic ACI | Yes
|Dimitri Sarafinof |IGN | Yes
|===
