// NOTE: Including an extra heading level for conformance class alone in their section
==== Core

[[rc_table-core]]

[requirements_class]
.Core
====
[%metadata]
identifier:: http://www.opengis.net/spec/symbology-1/2.0/req/core
subject:: Style encodings and Renderers
====

[[req-core-rules]]
===== Style `stylingRules` property

[requirement]
====
[%metadata]
identifier:: /req/core/rules
part:: An Encoding SHALL support individually storing and preserving the order of each StylingRule constituting a Style.
part:: A Renderer SHALL support considering in order each individual StylingRule constituting a style.
part:: The Symbolizer properties specified in a StylingRule appearing later in a Style's list of rules and whose Selector
evaluates to true SHALL be interpreted as overriding all Symbolizer properties set by earlier rules.
====

[[req-core-nested]]
===== StylingRule `nestedRules` property

[requirement]
====
[%metadata]
identifier:: /req/core/nested
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-expressions]]
===== Identifier Expressions

[requirement]
====
[%metadata]
identifier:: /req/core/expressions
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-selector]]
===== StylingRule `selector` property

[requirement]
====
[%metadata]
identifier:: /req/core/selector
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-symbolizer]]
===== StylingRule `symbolizer` property

[requirement]
====
[%metadata]
identifier:: /req/core/symbolizer
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-parameters]]
===== Symbolizer properties Parameter Values

[requirement]
====
[%metadata]
identifier:: /req/core/parameters
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-visibility]]
===== Symbolizer `visibility` property

[requirement]
====
[%metadata]
identifier:: /req/core/visibility
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-opacity]]
===== Symbolizer `opacity` property

[requirement]
====
[%metadata]
identifier:: /req/core/opacity
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-zorder]]
===== Symbolizer `zOrder` property

[requirement]
====
[%metadata]
identifier:: /req/core/zorder
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-literals]]
===== Literal Expressions

[requirement]
====
[%metadata]
identifier:: /req/core/literals
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-identifiers]]
===== Identifier Expressions

[requirement]
====
[%metadata]
identifier:: /req/core/identifiers
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-scale]]
===== Visualization Scale Denominator System Identifiers

[requirement]
====
[%metadata]
identifier:: /req/core/scale
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-time]]
===== Visualization Time System Identifiers

[requirement]
====
[%metadata]
identifier:: /req/core/time
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-layers]]
===== Data Layer System Identifiers

[requirement]
====
[%metadata]
identifier:: /req/core/layers
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-operations]]
===== Operation Expressions

[requirement]
====
[%metadata]
identifier:: /req/core/operations
part:: An Encoding SHALL support defining operation expressions consisting of operands and an operator for unary, binary and ternary operators.
part:: An Encoding SHALL support defining the priority of expressions using multiple operators (e.g., using parentheses: `(` `)`).
part:: A Renderer SHALL support evaluating operation expressions while respecting the priority of operations.
====

[[req-core-logical]]
===== Logical Operation Expressions

[requirement]
====
[%metadata]
identifier:: /req/core/logical
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-relational]]
===== Relational Operation Expressions

[requirement]
====
[%metadata]
identifier:: /req/core/relational
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-arrays]]
===== Array Expressions

[requirement]
====
[%metadata]
identifier:: /req/core/arrays
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-instances]]
===== Instance Expressions

[requirement]
====
[%metadata]
identifier:: /req/core/instances
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-default-values]]
==== Default class member values

[requirement]
====
[%metadata]
identifier:: /req/core/default-values
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====
