@startuml
class Expression <<abstract>>

LiteralExpression --|> Expression

IdentifierExpression : name: string

IdentifierExpression --|> Expression

VariableExpression : name: string

VariableExpression --|> Expression

InstanceExpression : objectClass: type
InstanceExpression : members: map < string, Expression >

InstanceExpression --|> Expression
InstanceExpression --* Expression

InstanceLiteral : <<concept: fixed members>>

InstanceLiteral --|> InstanceExpression
InstanceLiteral --|> LiteralExpression

class LiteralExpression <<abstract>>

TextLiteral : text: string

TextLiteral --|> LiteralExpression

EnumValueLiteral : enum: type
EnumValueLiteral : value: string
EnumValueLiteral : numericValue: int64

EnumValueLiteral --|> LiteralExpression

class BoolLiteral <<enumeration>>
BoolLiteral : false
BoolLiteral : true

BoolLiteral --|> EnumValueLiteral

NullLiteral --|> LiteralExpression

IntegerLiteral : value: int64

IntegerLiteral --|> LiteralExpression

RealLiteral : value: double

RealLiteral --|> LiteralExpression

'class SubExpression
'SubExpression --|> Expression -- Parentheses could be purely an encoding concept based on the need to maintain priority...
'class ExpressionList -- Expression with multiplicity?

ArrayExpression : elements: Expression[0..*]

ArrayExpression --|> Expression
ArrayExpression --* Expression

class ArrayLiteral <<concept: fixed elements>>

ArrayLiteral --|> ArrayExpression
ArrayLiteral --|> LiteralExpression

OperationExpression : operand1: Expression[0..1]
OperationExpression : operator: Operator
OperationExpression : operand2: Expression

OperationExpression --|> Expression
OperationExpression --* Operator
OperationExpression --* Expression

ConditionalExpression : condition: Expression
ConditionalExpression : thenExp: Expression
ConditionalExpression : elseExp: Expression

ConditionalExpression --|> Expression
ConditionalExpression --* Expression

FunctionCallExpression : function: Function
FunctionCallExpression : arguments: Expression[0..*]

FunctionCallExpression --|> Expression
FunctionCallExpression --* Function
FunctionCallExpression --* Expression

Function : name: string
Function : parameters: map < string, type >
Function : returnType: type

SystemIdentifierExpression --|> IdentifierExpression
@enduml