@startuml
'Class definition

Color : r: float
Color : g: float
Color : b: float

class StrokeJoin <<enumeration>>
StrokeJoin : miter
StrokeJoin : round
StrokeJoin : bevel

class StrokeCap <<enumeration>>
StrokeCap : butt
StrokeCap : round
StrokeCap : square

class GraphicalUnit <<enumeration>>
GraphicalUnit : pixels
GraphicalUnit : meters
GraphicalUnit : feet
GraphicalUnit : percent
GraphicalUnit : points
GraphicalUnit : em
GraphicalUnit : screenInches
GraphicalUnit : screenCM
GraphicalUnit : screenMM

StrokeStyling : color: Color
StrokeStyling : opacity: float
StrokeStyling : width: float
StrokeStyling : widthUnit: GraphicalUnit

Stroke : pattern: Graphic [0..1]
Stroke : center: StrokeStyling [0..1]
Stroke : casing: StrokeStyling [0..1]
Stroke : join: StrokeJoin [0..1]
Stroke : cap: StrokeCap [0..1]
Stroke : dashPattern: integer [*]

'Relations

'Inheritance

Stroke --|> StrokeStyling
Shape --|> Graphic

'Composition

Shape --* Stroke

StrokeStyling --* Color
StrokeStyling --* GraphicalUnit
Stroke --* Graphic
Stroke --* StrokeStyling
Stroke --* StrokeJoin
Stroke --* StrokeCap
VectorSymbolizer --* Stroke
@enduml