@startuml
'Class definition

TextAlignment : horizontal: HAlignment
TextAlignment : vertical: VAlignment
    
class HAlignment <<enumeration>>
HAlignment : left
HAlignment : center
HAlignment : right
    
class VAlignment <<enumeration>>
VAlignment : top
VAlignment : middle
VAlignment : bottom
    
FontOutline : size: float
FontOutline : opacity: float
FontOutline : color: Color

Font : face: string
Font : size: float
Font : bold: bool
Font : italic: bool
Font : underline: bool
Font : color: Color
Font : opacity: float
Font : outline: FontOutline
    
Color : r: float
Color : g: float
Color : b: float

Text : text: string
Text : font: Font
Text : alignment: TextAlignment
    
'Relations

'Inheritance
Text --|> Graphic

'Composition
Text --* Font
Text --* TextAlignment
Font --* FontOutline
Font --* Color
FontOutline --* Color
TextAlignment --* HAlignment
TextAlignment --* VAlignment

@enduml


