[appendix,obligation="informative"]
[[annex-sldse]]
== Mapping of SLD/SE and notable vendor extensions to the Conceptual Model

This annex maps constructs of the OGC Styled Layer Descriptor (SLD) and Symbology Encoding (SE) 1.1
to the conceptual model and requirements classes defined in this Standard, with the goal of facilitating
conformance to this Standard for Rendering engines based on SLD/SE and writing conversion tools
that can convert in either or both direction between SLD/SE and the two encodings defined in this
Standard.

=== Requirements Class "Core"

.Mapping of the "Core" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct         | SE Equivalent
| *Symbology Core*  | 
| Style             | `<UserStyle>`
| StylingRule       | `<Rule>`
| Symbolizer        | `<PointSymbolizer>`, `<LineSymbolizer>`, `<PolygonSymbolizer>`, `<TextSymbolizer>`, `<RasterSymbolizer>`
| Selector          | `<ogc:Filter>`, `<ogc:Function>`
| nestedRules       | N/A

| *Literal Expression* | 
| LiteralExpression | Literal values (strings, numbers, booleans) within SLD expressions
| TextLiteral       | `<ogc:Literal>`
| BoolLiteral       | Boolean literals (`<ogc:Literal>` with value "true" or "false")
| NullLiteral       | `<ogc:Null>`
| IntegerLiteral    | `<ogc:Literal>` with integer value
| RealLiteral       | Real (floating-point) literals (`<ogc:Literal>` with double value)
| ArrayLiteral      | Array literals (constructed using `<ogc:Literal>` elements)
| InstanceLiteral   | `<ogc:PropertyName>`

| *Expression*         | 
| Expression           | `<ogc:Filter>`, `<ogc:Function>`
| IdentifierExpression | `<ogc:PropertyName>`, `<ogc:Literal>`
| InstanceExpression   | `<ogc:Literal>`, `<ogc:PropertyName>`
| ArrayExpression      | `<ogc:Literal>` elements within `<ogc:Function>` or `<ogc:Filter>`

| *Core Logic and Relational Operators* | 
| Operator          | Comparison operators (`<ogc:PropertyIsEqualTo>`, `<ogc:PropertyIsLessThan>`, etc.)
| LogicOperator     | Logical operators (`<ogc:And>`, `<ogc:Or>`, `<ogc:Not>`)
|===

.SLD Example encoding style using "Core" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Core</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <ogc:Filter>
                  <ogc:PropertyIsEqualTo>
                     <ogc:PropertyName>landuse</ogc:PropertyName>
                     <ogc:Literal>parking</ogc:Literal>
                  </ogc:PropertyIsEqualTo>
               </ogc:Filter>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">#FF0000</CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
                  <stroke>
                     <CssParameter name="stroke">#000000</CssParameter>
                     <CssParameter name="stroke-width">1</CssParameter>
                  </stroke>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
<StyledLayerDescriptor>
----
====

=== Requirements Class "Parameter Values"

.Mapping of the "Parameter Values" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                      | SE Equivalent
| visualization                  | `<UserStyle>`
| dataLayer                      | `<UserStyle>`, `<RasterSymbolizer>`, `<PointSymbolizer>`, `<LineSymbolizer>`, `<PolygonSymbolizer>`, `<TextSymbolizer>`
| visualization.scaleDenominator | `<MaxScaleDenominator>`, `<MinScaleDenominator>`
| visualization.dateTime         | `<ogc:Literal>` with date and time value
| visualization.date             | `<ogc:Literal>` with date value
| visualization.timeOfDay        | `<ogc:Literal>` with time value
| visualization.pass             | `<ogc:Literal>` with integer value
| dataLayer.identifier           | `<ogc:PropertyName>`
| dataLayer.type                 | `<UserStyle>`, `<RasterSymbolizer>`, `<PointSymbolizer>`, `<LineSymbolizer>`, `<PolygonSymbolizer>`, `<TextSymbolizer>`
|===

.SLD Example encoding style using "Parameter Values" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
  <NamedLayer>
    <Name>Landuse</Name>
    <UserStyle>
      <Name>Styling a land use layer</Name>
      <Title>Styling a land use layer</Title>
      <Abstract>Styling land use data with Style &amp; Symbology Parameter Values</Abstract>
      <FeatureTypeStyle>
        <Rule>
          <Name>parking</Name>
          <Filter>
            <PropertyIsEqualTo>
              <PropertyName>landuse</PropertyName>
              <Literal>parking</Literal>
            </PropertyIsEqualTo>
          </Filter>
          <MaxScaleDenominator>200000</MaxScaleDenominator>
          <PolygonSymbolizer>
            <Fill>
              <CssParameter name="fill">#ff0000</CssParameter>
            </Fill>
            <Stroke>
              <CssParameter name="stroke">#000000</CssParameter>
              <CssParameter name="stroke-width">1</CssParameter>
            </Stroke>
          </PolygonSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Basic Vector Features Styling"

.Mapping of the "Basic Vector Features Styling" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                   | SE Equivalent
| Text                        | `<TextSymbolizer>`
| Font                        | `<CssParameter>` within `<TextSymbolizer>`
| TextAlignment               | `<TextSymbolizer>`
| HAlignment                  | `<TextSymbolizer>`
| VAlignment                  | `<TextSymbolizer>`
| Image                       | `<Graphic>`
| Dot                         | `<PointSymbolizer>`
| Shape                       | `<PointSymbolizer>`, `<LineSymbolizer>`, `<PolygonSymbolizer>`
| Marker                      | `<Graphic>`
| GraphicalUnit               | N/A
| Stroke                      | `<Stroke>`
| Fill                        | `<Fill>`
| Color                       | `<CssParameter>`
|===


.SLD Example encoding style using "Basic Vector Features Styling" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
  <NamedLayer>
    <Name>Landuse</Name>
    <UserStyle>
      <Name>Styling a land use layer</Name>
      <Title>Styling a land use layer</Title>
      <Abstract>Styling land use data with Style &amp; Symbology Parameter Values</Abstract>
      <FeatureTypeStyle>
        <Rule>
          <Name>parking</Name>
          <Filter>
            <PropertyIsEqualTo>
              <PropertyName>landuse</PropertyName>
              <Literal>parking</Literal>
            </PropertyIsEqualTo>
          </Filter>
          <MaxScaleDenominator>200000</MaxScaleDenominator>
          <PointSymbolizer>
            <Graphic>
              <ExternalGraphic>
                <OnlineResource xlink:type="simple" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Parking_icon.svg/128px-Parking_icon.svg.png"/>
              </ExternalGraphic>
            </Graphic>
          </PointSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Basic Coverage Styling"

.Mapping of the "Basic Coverage Styling" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| ColorChannels                | `<ColorMap>`
| AlphaChannel                 | `<RasterSymbolizer>`
| SingleChannel                | `<RasterSymbolizer>`
| ColorMap                     | `<ColorMap>`
| OpacityMap                   | `<ColorMap>`
| ValueColor                   | `<ColorMapEntry>`
| ValueOpacity                 | `<ColorMapEntry>`

|*Hill Shading*                |
| Construct                    | SE Equivalent
| AzimuthElevation             | `<AzimuthElevation>`
| HillShading                  | `<HillShading>`
| Symbolizer                   | `<Symbolizer>`

|*Coverage as points*          |
| mark                         | N/A

|*Coverage as contours*        |
| ContourSettings              | N/A

|*Contrast Enhancement*        |
| contrastEnhancement          | `<ContrastEnhancement>`

|*Hue, Saturation, Value Modifier* |
| hsvModifier                 | N/A
|===

.SLD Example encoding style rendering DEM with a color map using "Basic Coverage Styling" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.1.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
   <NamedLayer>
      <Name>Elevation</Name>
      <UserStyle>
         <Name>DEM with color map</Name>
         <Abstract>Applying a color map to a Digital Elevation Model with Style &amp; Symbology Basic Coverage Styling</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>DEM with color map</Name>
               <Title>DEM with color map</Title>
               <MaxScaleDenominator>200000</MaxScaleDenominator>
               <sld:RasterSymbolizer>
                  <sld:Opacity>0.8</sld:Opacity>
                  <sld:ChannelSelection>
                     <sld:GrayChannel>
                        <sld:SourceChannelName>elevation</sld:SourceChannelName>
                     </sld:GrayChannel>
                  </sld:ChannelSelection>
                  <sld:ColorMap>
                     <sld:ColorMapEntry color="#608849" quantity="0" label="0"/>
                     <sld:ColorMapEntry color="#E2DBA7" quantity="900" label="900"/>
                     <sld:ColorMapEntry color="#FCC575" quantity="1300" label="1300"/>
                     <sld:ColorMapEntry color="#FCA886" quantity="1900" label="1900"/>
                     <sld:ColorMapEntry color="#FAFAFA" quantity="2500" label="2500"/>
                  </sld:ColorMap>
               </sld:RasterSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Basic Labeling"

.Mapping of the "Basic Labeling" & "Font Outlines" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SLD Equivalent
| Label                        | `<TextSymbolizer>`
| LabelPlacement               | `<LabelPlacement>`
| ImageOutline                 | `<Graphic>`
| Font                         | `<CssParameter>` within `<TextSymbolizer>`
| FontOutline                  | `<CssParameter>` within `<TextSymbolizer>`
|===

.SLD Example encoding style using "Basic Labeling" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.1.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Basic Labeling</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <TextSymbolizer>
                <Label>
                  <ogc:PropertyName>name</ogc:PropertyName>
                </Label>
                <Font>
                  <CssParameter name="font-family">Arial</CssParameter>
                  <CssParameter name="font-size">12</CssParameter>
                  <CssParameter name="font-style">normal</CssParameter>
                  <CssParameter name="font-weight">bold</CssParameter>
                </Font>
                <LabelPlacement>
                  <PointPlacement>
                    <AnchorPoint>
                      <AnchorPointX>0.5</AnchorPointX>
                      <AnchorPointY>0.0</AnchorPointY>
                    </AnchorPoint>
                    <Displacement>
                      <DisplacementX>0</DisplacementX>
                      <DisplacementY>25</DisplacementY>
                    </Displacement>
                    <Rotation>-45</Rotation>
                  </PointPlacement>
                </LabelPlacement>
                <Fill>
                  <CssParameter name="fill">#990099</CssParameter>
                </Fill>
               </TextSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

// === Requirements Class "Image Outlines"
// Unnecessary, as the examples are already provided in the "Basic Vector Features Styling" requirements class.

=== Requirements Class "Shape Graphics"

.Mapping of the "Shape Graphics" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| Shape                        | `<PointSymbolizer>`, `<LineSymbolizer>`, `<PolygonSymbolizer>`
| Line                         | `<LineSymbolizer>`
| Polyline                     | `<LineSymbolizer>`
| Polygon                      | `<PolygonSymbolizer>`
| Rectangle                    | `<PolygonSymbolizer>`
| RoundedRectangle             | `<PolygonSymbolizer>`
| Circle                       | `<PointSymbolizer>`
| Ellipse                      | `<PointSymbolizer>`
| Arc                          | `<PointSymbolizer>`
| SectorArc                    | `<PointSymbolizer>`
| ChordArc                     | `<PointSymbolizer>`
| Path                         | `<LineSymbolizer>`, `<PolygonSymbolizer>`
| ClosedPath                   | `<PolygonSymbolizer>`
|===

.SLD Example encoding style using "Shape Graphics" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Shape Graphics</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PointSymbolizer>
                  <Graphic>
                     <Mark>
                        <WellKnownName>circle</WellKnownName>
                        <Fill>
                           <CssParameter name="fill">#FFA500</CssParameter>
                        </Fill>
                     </Mark>
                  </Graphic>
               </PointSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Shape Outlines"

.Mapping of the "Shape Outlines" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| thickness                    | `<CssParameter>` within `<Stroke>`
|===

.SLD Example encoding style using "Shape Outlines" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Shape Outlines</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">#FF0000</CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
                  <Stroke>
                     <CssParameter name="stroke">#000000</CssParameter>
                     <CssParameter name="stroke-width">1</CssParameter>
                  </Stroke>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Multi Graphics and Transforms"

.Mapping of the "Multi Graphics and Transforms" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| MultiGraphic                 | `<Graphic>`
| Transforms                   | `<Graphic>`
| GraphicInstance              | `<Graphic>`
|===

.SLD Example encoding style using "Multi Graphics and Transforms" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Multi Graphics and Transforms</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PointSymbolizer>
                  <Graphic>
                     <Mark>
                        <WellKnownName>circle</WellKnownName>
                        <Fill>
                           <CssParameter name="fill">#FFA500</CssParameter>
                        </Fill>
                     </Mark>
                     <Size>12</Size>
                     <Rotation>45</Rotation>
                  </Graphic>
               </PointSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Joins and Caps"

.Mapping of the "Joins and Caps" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| join                         | `<Stroke>`
| cap                          | `<Stroke>`
|===

.SLD Example encoding style using "Joins and Caps" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Joins and Caps</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <LineSymbolizer>
                  <Stroke>
                     <CssParameter name="stroke">#000000</CssParameter>
                     <CssParameter name="stroke-width">1</CssParameter>
                     <CssParameter name="stroke-linejoin">round</CssParameter>
                     <CssParameter name="stroke-linecap">round</CssParameter>
                  </Stroke>
               </LineSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Dashes"

.Mapping of the "Dashes" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| dashPattern                  | `<Stroke>`
| dashOffset                   | `<Stroke>`
|===

.SLD Example encoding style using "Dashes" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Dashes</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <LineSymbolizer>
                  <Stroke>
                     <CssParameter name="stroke">#000000</CssParameter>
                     <CssParameter name="stroke-width">1</CssParameter>
                     <CssParameter name="stroke-dasharray">5 2 1 2</CssParameter>
                     <CssParameter name="stroke-dashoffset">2</CssParameter>
                  </Stroke>
               </LineSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Casing and Centerline"

.Mapping of the "Casing and Centerline" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| casing                       | `<Stroke>`
| center                       | `<Stroke>`
|===

.SLD Example encoding style using "Casing and Centerline" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Casing and Centerline</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <LineSymbolizer>
                  <Stroke>
                     <CssParameter name="stroke">#000000</CssParameter>
                     <CssParameter name="stroke-width">1</CssParameter>
                  </Stroke>
                  <Stroke>
                     <CssParameter name="stroke">#FFFFFF</CssParameter>
                     <CssParameter name="stroke-width">3</CssParameter>
                  </Stroke>
               </LineSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Pattern Strokes"

.Mapping of the "Pattern Strokes" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| pattern                      | `<Graphic>`
| patternGap                   | `<Stroke>`
| patternInitialGap            | `<Stroke>`
|===

.SLD Example encoding style using "Pattern Strokes" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" version="1.0.0">
  <NamedLayer>
    <UserStyle>
      <Name>Trails</Name>
      <Title/>
      <FeatureTypeStyle>
        <Rule>
          <MaxScaleDenominator>75000</MaxScaleDenominator>
          <LineSymbolizer>
            <Stroke>
              <GraphicStroke>
                <Graphic>
                  <Mark>
                    <WellKnownName>circle</WellKnownName>
                    <Fill>
                      <CssParameter name="fill">#AA0000</CssParameter>
                    </Fill>
                  </Mark>
                  <Size>
                    <ogc:Literal>6</ogc:Literal>
                  </Size>
                </Graphic>
              </GraphicStroke>
              <CssParameter name="stroke-dasharray">6 18</CssParameter>
            </Stroke>
          </LineSymbolizer>
          <LineSymbolizer>
            <Stroke>
              <CssParameter name="stroke">#AA0000</CssParameter>
              <CssParameter name="stroke-dasharray">10 14</CssParameter>
              <CssParameter name="stroke-dashoffset">14</CssParameter>
            </Stroke>
          </LineSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
----
====

// === Requirements Class "Pattern Fills"
// Unnecessary, as the examples are already provided in the "Pattern Strokes" requirements class.

=== Requirements Class "Hatches and Gradients, Stipples"

.Mapping of the "Hatches and Gradients, Stipples" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
|*Hatches, Gradients and Stipple Fills* |
| hatchStyle                   | `<HatchPattern>`
| stippleStyle                 | `<StipplePattern>`

|*Gradients*                   |
| percent                      | `<CssParameter>` within `<Fill>`
| gradient                     | `<Fill>`
| GradientType                 | `<LinearGradient>`, `<RadialGradient>`, `<ConicGradient>`, `<RepeatingGradient>`

|*Stipples*                    |
| StippleStyle                 | `<StipplePattern>`

|*Hatches*                     |
| HatchStyle                   | `<HatchPattern>`
|===

.SLD Example encoding style using "Hatches and Gradients, Stipples" requirements class
====
[source,sld]
----
?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor
xmlns="http://www.opengis.net/sld"
xmlns:sld="http://www.opengis.net/sld"
xmlns:ogc="http://www.opengis.net/ogc"
xmlns:gml="http://www.opengis.net/gml"
xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0.0">
  <NamedLayer>
    <UserStyle>
      <Name>tl 2010 08013 arealm</Name>
      <Title/>
      <FeatureTypeStyle>
        <Rule>
          <Name>cemeteries</Name>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>MTFCC</ogc:PropertyName>
              <ogc:Literal>K2582</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <MaxScaleDenominator>500000.0</MaxScaleDenominator>
          <sld:PolygonSymbolizer>
            <Fill>
              <GraphicFill>
                <Graphic>
                  <sld:ExternalGraphic>
                    <sld:OnlineResource
                    xlink:type="simple"
                    xlink:href="./img/landmarks/area/grave_yard.png" />
                    <sld:Format>image/png</sld:Format>
                  </sld:ExternalGraphic>
                </Graphic>
              </GraphicFill>
            </Fill>
          </sld:PolygonSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
----
====

// === Requirements Class "Symbolizer Parameter Value Expressions"
// Unnecessary, as the examples are already provided in the "Parameter Values" requirements class.

// === Requirements Class "Any right-hand operands"
// Unnecessary, as the examples are already provided in the "Core" requirements class.

=== Requirements Class "Conditional Expressions"

.Mapping of the "Conditional Expressions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SLD Equivalent
| ConditionalExpression        | `<ogc:Function>`
| condition                    | `<ogc:Function>`
| thenExp                      | `<ogc:Function>`
| elseExp                      | `<ogc:Function>`
|===

.SLD Example encoding style using "Conditional Expressions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Conditional Expressions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="if_then_else">
                           <ogc:Function name="PropertyIsEqualTo">
                              <ogc:PropertyName>landuse</ogc:PropertyName>
                              <ogc:Literal>parking</ogc:Literal>
                           </ogc:Function>
                           <ogc:Literal>#FF0000</ogc:Literal>
                           <ogc:Literal>#00FF00</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Variables"

.Mapping of the "Variables" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| VariableExpression           | `<ogc:PropertyName>`
|===

.SLD Example encoding style using "Variables" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Variables</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:PropertyName>landuse</ogc:PropertyName>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Arithmetic Operators"

.Mapping of the "Arithmetic Operators" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| ArithmeticOperator           | `<ogc:Function>`
| add                          | `<ogc:Function>`
| sub                          | `<ogc:Function>`
| mul                          | `<ogc:Function>`
| div                          | `<ogc:Function>`
| intDiv                       | N/A
| mod                          | N/A
| pow                          | N/A
|===

.SLD Example encoding style using "Arithmetic Operators" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Arithmetic Operators</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="add">
                           <ogc:PropertyName>landuse</ogc:PropertyName>
                           <ogc:Literal>parking</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Bitwise Operators"

.Mapping of the "Bitwise Operators" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| BitwiseOperator              | `<ogc:Function>`
| bitAnd                       | `<ogc:Function>`
| bitOr                        | `<ogc:Function>`
| bitNot                       | `<ogc:Function>`
| bitXor                       | N/A
| leftShift                    | N/A
| rightShift                   | N/A
|===

.SLD Example encoding style using "Bitwise Operators" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Bitwise Operators</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="bitAnd">
                           <ogc:PropertyName>landuse</ogc:PropertyName>
                           <ogc:Literal>parking</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Text Relation Operators"

.Mapping of the "Text Relation Operators" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                     | SE Equivalent
| TextRelationOperator          | `<ogc:Function>`
| like                          | `<ogc:Function>`
| notLike                       | `<ogc:Function>`
| contains                      | `<ogc:Function>`
| startsWith                    | `<ogc:Function>`
| endsWith                      | `<ogc:Function>`
| notContains                   | `<ogc:Function>`
| notStartsWith                 | `<ogc:Function>`
| notEndsWith                   | `<ogc:Function>`
| like                          | `<ogc:Function>`
| notLike                       | `<ogc:Function>`
| contains                      | `<ogc:Function>`
| startsWith                    | `<ogc:Function>`
| endsWith                      | `<ogc:Function>`
| notContains                   | `<ogc:Function>`
| notStartsWith                 | `<ogc:Function>`
| notEndsWith                   | `<ogc:Function>`
|===

.SLD Example encoding style using "Text Relation Operators" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Text Relation Operators</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="like">
                           <ogc:PropertyName>landuse</ogc:PropertyName>
                           <ogc:Literal>parking</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Function Expressions"

.Mapping of the "Function Expressions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| FunctionCallExpression       | `<ogc:Function>`
| Function                     | `<ogc:Function>`
| uri                          | `<ogc:Function>`
|===

.SLD Example encoding style using "Function Expressions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Function Expressions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="uri">
                           <ogc:Literal>http://www.opengis.net/ogc</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Math Functions"

.Mapping of the "Math Functions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| MathFunctions                | `<ogc:Function>`
| abs                          | N/A
| acos                         | N/A
| asin                         | N/A
| atan                         | N/A
| atan2                        | N/A
| ceil                         | N/A
| cos                          | N/A
| cosh                         | N/A
| exp                          | N/A
| floor                        | N/A
| log                          | N/A
| log10                        | N/A
| max                          | N/A
| min                          | N/A
| pow                          | N/A
| random                       | N/A
| rint                         | N/A
| round                        | N/A
| sin                          | N/A
| sinh                         | N/A
| sqrt                         | N/A
| tan                          | N/A
| tanh                         | N/A
|===

.SLD Example encoding style using "Math Functions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Math Functions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="round">
                           <ogc:PropertyName>surface</ogc:PropertyName>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Spatial Relation Functions"

.Mapping of the "Spatial Relation Functions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| SpatialRelationFunctions     | `<ogc:Function>`
| s_intersects                 | `<ogc:Function>`
| s_contains                   | `<ogc:Function>`
| s_crosses                    | `<ogc:Function>`
| s_disjoint                   | `<ogc:Function>`
| s_equals                     | N/A
| s_overlaps                   | `<ogc:Function>`
| s_touches                    | `<ogc:Function>`
| s_within                     | `<ogc:Function>`
| s_covers                     | N/A
| s_coveredBy                  | N/A
|===

.SLD Example encoding style using "Spatial Relation Functions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Spatial Relation Functions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="intersects">
                           <ogc:PropertyName>landuse</ogc:PropertyName>
                           <ogc:Literal>parking</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Temporal Relation Functions"

.Mapping of the "Temporal Relation Functions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| TemporalRelationFunctions    | `<ogc:Function>`
| t_after                      | `<ogc:Function>`
| t_before                     | `<ogc:Function>`
| t_disjoint                   | `<ogc:Function>`
| t_equals                     | `<ogc:Function>`
| t_intersects                 | `<ogc:Function>`
| t_contains                   | `<ogc:Function>`
| t_during                     | `<ogc:Function>`
| t_finishedBy                 | `<ogc:Function>`
| t_finishes                   | `<ogc:Function>`
| t_meets                      | `<ogc:Function>`
| t_meetBy                     | `<ogc:Function>`
| t_overlappedBy               | `<ogc:Function>`
| t_overlaps                   | `<ogc:Function>`
| t_startedBy                  | `<ogc:Function>`
| t_starts                     | `<ogc:Function>`
|===

.SLD Example encoding style using "Temporal Relation Functions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Temporal Relation Functions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="t_after">
                           <ogc:PropertyName>date</ogc:PropertyName>
                           <ogc:Literal>2019-01-01</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Array Relation Functions"

.Mapping of the "Array Relation Functions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| ArrayRelationFunctions       | `<ogc:Function>`
| a_containedBy                | `<ogc:Function>`
| a_contains                   | `<ogc:Function>`
| a_equals                     | `<ogc:Function>`
| a_overlaps                   | `<ogc:Function>`
|===

.SLD Example encoding style using "Array Relation Functions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Array Relation Functions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="a_containedBy">
                           <ogc:PropertyName>landuse</ogc:PropertyName>
                           <ogc:Literal>parking</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Text Manipulation Functions"

.Mapping of the "Text Manipulation Functions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| TextManipulationFunctions    | `<ogc:Function>`
| caseInsensitize              | `<ogc:Function>`
| accentInsensitize            | `<ogc:Function>`
| lowerCase                    | `<ogc:Function>`
| upperCase                    | `<ogc:Function>`
| concatenate                  | `<ogc:Function>`
| substitute                   | `<ogc:Function>`
| format                       | `<ogc:Function>`
|===

.SLD Example encoding style using "Text Manipulation Functions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Text Manipulation Functions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <TextSymbolizer>
                  <Label>
                     <ogc:Function name="strCapitalize">
                        <ogc:PropertyName>landuse</ogc:PropertyName>
                     </ogc:Function>
                  </Label>
               </TextSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Geometry Manipulation Functions"

.Mapping of the "Geometry Manipulation Functions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                     | SE Equivalent
| GeometryManipulationFunctions | `<ogc:Function>`
| s_difference                  | N/A
| s_symDifference               | N/A
| s_convexHull                  | N/A
| s_buffer                      | N/A
| s_envelope                    | N/A
| s_centroid                    | N/A
| s_offsetCurve                 | N/A
| s_voronoiLines                | N/A
| s_voronoiPolygons             | N/A
| s_delaunayTriangles           | N/A
|===

.SLD Example encoding style using "Geometry Manipulation Functions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="ISO-8859-1"?>
<StyledLayerDescriptor version="1.0.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd">
  <NamedLayer>
    <Name>Default Point</Name>
    <UserStyle>
      <FeatureTypeStyle>
        <Rule>
          <LineSymbolizer>
            <Stroke/>
          </LineSymbolizer>
          <PointSymbolizer>
            <Geometry><ogc:Function name="vertices"><ogc:PropertyName>the_geom</ogc:PropertyName></ogc:Function></Geometry>
            <Graphic>
              <Mark>
                <WellKnownName>square</WellKnownName>
                <Fill>
                  <CssParameter name="fill">#FF0000</CssParameter>
                </Fill>
              </Mark>
              <Size>6</Size>
            </Graphic>
          </PointSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Recoding Function"

.Mapping of the "Recoding Function" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| recode                       | `<ogc:Function>`
|===

.SLD Example encoding style using "Recoding Function" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Recoding Function</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                    <CssParameter name="fill">
                      <ogc:Function name="Recode">
                        <!-- Value to transform -->
                        <ogc:Function name="strTrim">
                          <ogc:PropertyName>SUB_REGION</ogc:PropertyName>
                        </ogc:Function>
                        <!-- Map of input to output values -->
                        <ogc:Literal>N Eng</ogc:Literal>
                        <ogc:Literal>#6495ED</ogc:Literal>
                        <ogc:Literal>Mid Atl</ogc:Literal>
                        <ogc:Literal>#B0C4DE</ogc:Literal>
                        <ogc:Literal>S Atl</ogc:Literal>
                        <ogc:Literal>#00FFFF</ogc:Literal>
                        <ogc:Literal>E N Cen</ogc:Literal>
                        <ogc:Literal>#9ACD32</ogc:Literal>
                        <ogc:Literal>E S Cen</ogc:Literal>
                        <ogc:Literal>#00FA9A</ogc:Literal>
                        <ogc:Literal>W N Cen</ogc:Literal>
                        <ogc:Literal>#FFF8DC</ogc:Literal>
                        <ogc:Literal>W S Cen</ogc:Literal>
                        <ogc:Literal>#F5DEB3</ogc:Literal>
                        <ogc:Literal>Mtn</ogc:Literal>
                        <ogc:Literal>#F4A460</ogc:Literal>
                        <ogc:Literal>Pacific</ogc:Literal>
                        <ogc:Literal>#87CEEB</ogc:Literal>
                      </ogc:Function>
                    </CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Aggregation"

This requirements class is not supported by SLD/SE.

=== Requirements Class "3D Graphics, Models and Transforms"

This requirements class is not supported by SLD/SE.
