[appendix,obligation="normative"]
[[annex-ats]]
== Conformance Class Abstract Test Suite

A Symbology Encoding implementation shall satisfy the following characteristics to be conformant with this specification.

The OGC URI identifier of this conformance class is: http://www.opengis.net/spec/symbology/2.0/conf/core.

It is the root of the test identifiers described below.


==== Implements the Style class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/StyleClass"]
=====

[verification,label="/conf/core/StyleClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/StyleClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/req/core/StyleClass

Test method:: Review all rows of the Style class and confirm that an encoding rule is defined for each element in the encoding specification. Check that at least one concrete class of the Style class has an encoding rule defined.
======

=====

==== Implements the Rule class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/RuleClass"]
=====

[verification,label="/conf/core/RuleClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/RuleClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/req/core/StyleClass

Test method:: Review all rows of the Rule class and confirm that an encoding is defined for each element in the encoding specification.
======

=====

==== Implements the Symbolizer Class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/SymbolizerClass"]
=====

[verification,label="/conf/core/SymbolizerClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/SymbolizerClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/req/core/SymbolizerClass

Test method:: Review all rows of the Symbolizer class and confirm that an encoding rule is defined for each element in the encoding specification. Check that at least one concrete class of the Symbolizer class (defined by the symbology conceptual model) has an encoding rule defined.
======

=====

==== Implements the ParameterValue Class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/ParameterValueClass"]
=====

[verification,label="/conf/core/ParameterValueClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/ParameterValueClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/req/core/ParameterValueClass

Test method:: Review all rows of the ParameterValue class and confirm that an encoding rule is defined for each element in the encoding specification. Check that at least one concrete class (defined by the symbology conceptual model) of the ParameterValue abstract class is implemented.
======

=====


==== Implements the Literal class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/LiteralClass"]
=====

[verification,label="/conf/core/LiteralClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/LiteralClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/req/core/LiteralClass

Test method:: Review all rows of the Literal class and confirm that an encoding rule is defined for each element in the encoding specification.
======

=====

==== Implements the uom codelist
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/UOMClass"]
=====

[verification,label="/conf/core/UOMClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/UOMClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/req/core/UOMClass

Test method:: Check that at least the pixel portrayal unit of measure is implemented.
======

=====

==== Implements the Color Class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/ColorClass"]
=====

[verification,label="/conf/core/ColorClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/ColorClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/req/core/ColorClass

Test method:: Review all rows of the Color class and confirm that an encoding rule is defined for each element in the encoding specification. Check that at least one concrete class (defined by the symbology conceptual model) of the Color abstract class is implemented.
======

=====


==== Implements the Fill Class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/FillClass"]
=====

[verification,label="/conf/core/FillClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/FillClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/conf/req/FillClass

Test method:: Review all rows of the Fill class and confirm that an encoding rule is defined for each element in the encoding specification. Check that at least one concrete class (defined by the symbology conceptual model) of the Fill abstract class is implemented.
======

=====

==== Implements the Stroke Class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/StrokeClass"]
=====

[verification,label="/conf/core/StrokeClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/StrokeClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/conf/req/StrokeClass

Test method:: Review all rows of the Stroke class and confirm that an encoding rule is defined for each element in the encoding specification. Check that at least one concrete class (defined by the symbology conceptual model) of the Stroke abstract class is implemented.
======

=====

==== Implements the Graphic Class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/GraphicClass"]
=====

[verification,label="/conf/core/GraphicClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/GraphicClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/conf/req/GraphicClass

Test method:: Review all rows of the Graphic class and confirm that an encoding rule is defined for each element in the encoding specification. Check that at least one concrete class (defined by the symbology conceptual model) of the Graphic abstract class is implemented.
======

=====

==== Implements the GraphicSize Class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/GraphicSizeClass"]
=====

[verification,label="/conf/core/GraphicSizeClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/GraphicSizeClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/conf/req/GraphicClass

Test method:: Review all rows of the GraphicSize class and confirm that an encoding rule is defined for each element in the encoding specification.
======

=====


==== Implements the Label Class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/LabelClass"]
=====

[verification,label="/conf/core/LabelClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/LabelClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/conf/req/LabelClass

Test method:: Review all rows of the Label class and confirm that an encoding rule is defined for each element in the encoding specification. Check that at least one concrete class (defined by the symbology conceptual model) of the Label abstract class is implemented.
======

=====


==== Implements the Font Class
[requirement,type="pseudocode",label="http://www.opengis.net/spec/symbology/2.0/conf/core/FontClass"]
=====

[verification,label="/conf/core/FontClass"]
======
Test ID:: http://www.opengis.net/spec/symbology/2.0/conf/core/FontClass

Test purpose:: To test requirement http://www.opengis.net/spec/symbology/2.0/conf/req/FontClass

Test method:: Review all rows of the Font class and confirm that an encoding rule is defined for each element in the encoding specification.
======

=====
