[[rc-coverage]]
== Requirements Classes for Coverage styling

=== Requirements Class "Basic Coverage Styling"
==== Overview

This requirements class adds support for defining how to portray coverage data by mapping
values from the range (e.g., individual imagery bands) to color channels or to a single channel, as well
as providing an option to apply a color and/or opacity map based on the values.

[#img-uml-class-coverageSymbolizer]
.Extended Symbolizer Class UML Diagram
[plantuml, target=diagram-classes, format=png]
....
class Symbolizer <<extended>>
Symbolizer : colorChannels: Color -- IdentifierExpressions
Symbolizer : alphaChannel: double -- IdentifierExpression
Symbolizer : singleChannel: double -- IdentifierExpression
Symbolizer : colorMap: ValueColor[*]
Symbolizer : opacityMap: ValueOpacity[*]
Symbolizer --* ValueOpacity
Symbolizer --* ValueColor
Symbolizer --* Color
Symbolizer --> IdentifierExpression

ValueColor : value: double
ValueColor : color: Color
ValueColor : label: text
ValueColor --* Color

ValueOpacity : value: double
ValueOpacity : opacity: float
ValueOpacity : label: text

Color : r: float
Color : g: float
Color : b: float
....

===== Extended Identifiers

This requirements class defines as valid identifiers all of the accessible properties (the values of its range, as defined by the range type)
for a coverage being portrayed with the name of those properties being the text of the identifier.
Those identifiers are to be resolved with the value of that property.
An encoding must support an escaping mechanism in cases where the name of a feature property might clash with a syntactic element.

===== Extended Symbolizer

.Extended Symbolizer properties
[width="90%",options="header"]
|===
| Name              | Definition	                                  | Data type and value   | Multiplicity
| colorChannels     | Value of the Red, Green and Blue color channels | Color                 | 0..1
| alphaChannel      | Value of the alpha (opacity) channel            | float                 | 0..1
| singleChannel     | Value of a single (gray-scale) output channel   | float                 | 0..1
| colorMap          | Color map to be applied based on singleCannel   | ValueColor            | 0..*
| opacityMap        | Opacity map to be applied based on singleCannel | ValueOpacity          | 0..*
|===

This requirements class requires support for identifier parameter value expression for the red (`r`), green (`g`) and blue (`b`) components of
the `colorChannels`, `alphaChannel` and `singleChannel` properties without any additional requirements class.

This allows to map the range values of a coverage to the output color channels.

The color map is defined with a Value/Color pair object:

.ValueColor properties
[width="90%",options="header"]
|===
| Name                | Definition	                                         | Data type and value | Multiplicity
| value               | Key value for selecting this color                   | float               | 1
| color               | Color associated with this value                     | Color               | 1
| name                | Label to use for this value when generating a legend | string              | 0..1
|===

Similarly, the opacity map is defined with a Value/Opacity pair object:

.ValueOpacity properties
[width="90%",options="header"]
|===
| Name                | Definition	                                         | Data type and value | Multiplicity
| value               | Key value for selecting this color                   | float               | 1
| color               | Color associated with this value                     | Color               | 1
| name                | Label to use for this value when generating a legend | string              | 0..1
|===

===== Colors

Both the `colorChannels` and the `colorMap` properties use a Color class, specified using red, green and blue components.
The ability to define Colors in other spaces (e.g., Lab, CMYK) is defined in separate requirements classes
and applies wherever this basic RGB Color class is used.

.Color
[width="90%",options="header"]
|===
| Name	| Definition	| Data type and value	| Multiplicity
| r	   | Red          | float                 | 1
| g	   | Green        | float                 | 1
| b	   | Blue         | float                 | 1
|===

==== ContrastEnhancement

[#img-uml-class-contrastEnhancement]
.ContrastEnhancement class UML Diagram
[plantuml, target=diagram-classes, format=png]
....
class ContrastEnhancement <<extended>>
ContrastEnhancement : gamma: Gamma
ContrastEnhancement : histogram: Histogram
ContrastEnhancement : normalize: boolean

class Gamma <<extended>>
Gamma : gamma: float

class Histogram <<extended>>
Histogram : histogram: List<float>

class Normalize <<extended>>
Normalize : normalize: boolean

ContrastEnhancement "1" o-- "1" Gamma
ContrastEnhancement "1" o-- "1" Histogram
ContrastEnhancement "1" o-- "1" Normalize
....

.ContrastEnhancement properties
[width="90%",options="header"]
|===
| Name              | Definition	                                  | Data type and value   | Multiplicity
| gamma             | Gamma value to apply to the coverage            | float                 | 0..1
| histogram         | Histogram to apply to the coverage              | Histogram             | 0..1
| normalize         | Normalize the coverage values                   | boolean               | 0..1
|===

.Gamma properties
[width="90%",options="header"]
|===
| Name              | Definition	                                  | Data type and value   | Multiplicity
| gamma             | Gamma value to apply to the coverage            | float                 | 1
|===

.Histogram properties
[width="90%",options="header"]
|===
| Name              | Definition	                                  | Data type and value   | Multiplicity
| histogram         | Histogram to apply to the coverage              | List<float>           | 1
|===

.Normalize properties
[width="90%",options="header"]
|===
| Name              | Definition	                                  | Data type and value   | Multiplicity
| normalize         | Normalize the coverage values                   | boolean               | 1
|===

This requirements class adds the capability to apply a contrast enhancement to the coverage being portrayed.

==== Gradient

[#img-uml-class-gradient]
.Gradient class UML Diagram
[plantuml, target=diagram-classes, format=png]
....
@startuml
class Gradient {
  + type: GradientType
  + angle: float
  + position
  + colorStops: List<ColorStop>
  + size: Size
}

enum GradientType {
  linear
  radial
  repeating
  conic
}

class Size {
  + length: float
  + lengthPercentage: float
  + position: Position
}

enum Position {
  left
  center
  right
  top
  middle
  bottom
}

Gradient "1" o-- "1" GradientType
Gradient "1" o-- "1" Size

Gradient "1" o-- "1" Position
@enduml
....

A gradient is a graphical effect that produces a gradual transition between two or more colors. 3 main types of gradients are supported: linear, radial and conic. All of the parameters are inherited from their corresponding classes.

.Gradient class
[width="90%",options="header"]
|===
| Name       | Definition              | Type            | Multiplicity
GradientType | Type of gradient        | enum            | 1
angle        | Angle of gradient       | float           | 1
position     | Position of gradient    | Position        | 1
colorStops   | Color stops of gradient | List<ColorStop> | 1
size         | Size of gradient        | Size            | 1
|===

==== Requirements

include::../requirements/rc-coverage.adoc[]

[[rc-hillshading]]
=== Requirements Class "Hill Shading"
==== Overview

[#img-uml-class-hilldhading]
.Extended Symbolizer Class UML Diagram
[plantuml, target=diagram-classes, format=png]
....
AzimuthElevation : azimuth: Angle
AzimuthElevation : elevation: Angle
AzimuthElevation --* Angle

HillShading : factor: double
HillShading : sun: AzimuthElevation
HillShading : colorMap: ValueColor[*]
HillShading : opacityMap: ValueOpacity[*]
HillShading --* AzimuthElevation
HillShading --* ValueColor
HillShading --* ValueOpacity

class Symbolizer <<extended>>
Symbolizer : hillShading: HillShading
Symbolizer --* HillShading
....

This requirements classand adds the capability to portray elevation coverages with a hill shading style.
It depends on the _Basic Coverage Styling_ requirements class.

===== Extended Symbolizer

.Extended Symbolizer properties
[width="90%",options="header"]
|===
| Name                          	| Definition	                                   | Data type and value   | Multiplicity
| hillShading                    | Hill shading parameters                         | HillShading           | 0..1
|===

.HillShading properties
[width="90%",options="header"]
|===
| Name                          	| Definition	                                       | Data type and value   |Multiplicity
| factor                         | Factor controlling the intensity of the shading     | float                 | 0..1
| sun                            | Orientation of the sun                              | AzimuthElevation      | 0..1
| colorMap                       | Color map to be applied based on calculated shade   | ValueColor            | 0..*
| opacityMap                     | Opacity map to be applied based on calculated shade | ValueOpacity          | 0..*
|===

The `sun` property is specified using this AzimuthElevation class:

.AzimuthElevation properties
[width="90%",options="header"]
|===
| Name                          	| Definition	                                       | Data type and value   |Multiplicity
| azimuth                        | Azimuth angle relative to North                     | Angle                 | 0..1
| elevation                      | Elevation angle relative to the ground              | Angle                 | 0..1
|===

==== Requirements
==== OverlapBehavior
  
[#img-uml-class-overlapBehavior]
.OverlapBehavior class UML Diagram
[plantuml, target=diagram-classes, format=png]
....
class OverlapBehavior <<extended>>
OverlapBehavior : LatestOnTop: boolean
OverlapBehavior : earliestOnTop: boolean
OverlapBehavior : average: boolean
OverlapBehavior : random: boolean
....

This requirements class adds the capability to specify how to portray coverages that overlap in the same location.

==== Coverage to Feature transformation

[#img-uml-class-coverageToFeatureTransformation]
.CoverageToFeatureTransformation class UML Diagram
[plantuml, target=diagram-classes, format=png]
....
class CoverageToFeatureTransformation <<extended>>
CoverageToFeatureTransformation : PointCollection: PointCollection
CoverageToFeatureTransformation : Contour: Contour
....

// add an example with windbarbs (see https://docs.geoserver.org/main/en/user/styling/css/styledmarks.html)
// another example (contour) could be hypsometric tints (see https://www.sarahbellmaps.com/drawing-color-hillshade-a-tutorial-with-time-lapse-videos)

This requirements class adds the capability to transform a coverage into a feature collection.

include::../requirements/rc-hillshading.adoc[]
