[[rc-ccsss]]
== Requirements Class "Cascading Cartographic Symbology Style Sheets"

=== Overview

This requirements class defines an encoding for the Styles and Symbology Logical Model inspired from Web Cascading Style Sheets (CSS) and other CSS-like cartographic symbology encodings.
The primary objective of this encoding is expressiveness so as to facilitate hand-edition by cartographers.
Parsing this encoding requires a custom parser.

==== Cascading Style Sheets

A style is encoded as a series of styling rules into a _style sheet_ document.
Symbolizer properties set further down in rules override those set by rules at the same level apearing earlier (higher up).

It is also possible to include another style sheet using the `.include` directive followed by a relative path enclosed within single quotes (`'` `'`), separated by a space e.g., `.include '../baseStyle.ccsss'`.
The include directive is replaced by the content of that file in a pre-processing step in a recursive manner, so that style sheets can be _cascaded_.

Because later rules allow to override earlier ones, this cascading allows to apply for example:

* run-time styling preferences over default user styling,
* user styling preferences over default application styling,
* application styling preferences over default data provider styling.

==== Comments

A style sheet can also contain comments either using C-style multi-line comments (between `/\*` and `*/`) or C++-style single-line comments (starting with `//`).

==== Metadata elements

In addition to styling rules, the style sheet can define metadata elements prefixed by a dot (`.`) as the first character on a line.
The following metadata elements are defined:

.Metadata elements
[width="90%",options="header"]
|===
| Name           | Definition
| title          | Short human-readable title for the style
| abstract       | Detailed description of the style
| authors        | Authors of the style
| geoDataClasses | Comma-separated URIs of GeoDataClasses allowing to identify data sources for which the style is suitable
|===

NOTE: We should probably include these metadata elements in Core conceptual model.

==== Styling Rules and Symbolizers

A styling rule applies zero or more symbolizer properties if its Selector is evaluated to _true_.
A styling rule may also include nested rules that are only evaluated when the parent rule itself is selected.
Symbolizer properties set within a nested rule override symbolizer properties set in the parent rule.
It is also possible to override only a portion of a property by assigning a value to member of an object,
or an element of an array.

The grammar for specifying a rule in this encoding is:

[<selector>]*
'`{`'
   [<symbolizer property assignment>]*
   [<nested rule>]*
'`}`'

The grammar for a symbolizer property assignment is:

<symbolizer property name>
   ['`.`' <member> | '`[`' <index> '`]`' ]*
   '`:`' <expression> '`;`'

==== Selectors

A selector is either:

* an expression as described in the <<ccsss,section below>> (combined together as a logical AND),
* or a short-hand form for selecting a data layer (combined between them as a logical OR, but combined with other selectors as a logical AND):

<data layer name>

[[ccsss]]
==== Expressions

===== CQL2-Text encoding

Whether in Selectors or values of property symbolizers, Expressions are encoded using http://docs.ogc.org/DRAFTS/21-065.html#cql2-text[CQL2-Text].
However, a number of extensions are introduced to cover the full range of capabilities defined by the styling and symbology conceptual model.

The first such extension is that in the context of a symbolizer property value, expressions are not limited to boolean predicates being
evaluated as true or false, but can return any type of values such as numerical, text, or complex values, including geometry.

===== Instance expressions

The concept of an object instance is introduced, with the grammar:

<Class Name> '`(`' <member initializer list> '`)`'.

This corresponds somewhat to CQL2 constructs for temporal intervals and WKT geometry for example,

* `POLYGON( (0 40, 10 40, 10 50, 0 50, 0 40) )`
* `INTERVAL('2021-01-01T00:00:00Z','2021-12-31T23:59:59Z')`

In the first example, POLYGON is the class name, and the array of coordinates is a list of a single member initializer.
In the second second example, INTERVAL is the class name, and the start and end dates are a list of two member initializers.

In both of these examples, the members being initialized are implied from the order.
Due to the heavy use of object instances in the symbology model, the ability to identify specific member to initialize is introduced.
The syntax for doing so tries to be consistent with the overall CSS inspiration, and therefore the <member> ':' value is used,
and the ';' is added as an alternative way to separate members in the initializer list.
As examples, the above instantiations could also be written:

* `POLYGON(rings: (0 40, 10 40, 10 50, 0 50, 0 40))`
* `INTERVAL(start: '2021-01-01T00:00:00Z'; end: '2021-12-31T23:59:59Z')`

Another capability introduced is the ability to infer the class from the expected type where the instance expression is used.
For example, if a POLYGON object is assigned to a `poly` property expecting that object type, then the expression can be written simply as:

* `(rings: (0 40, 10 40, 10 50, 0 50, 0 40))`

In both of these examples, the members being initialized are implied from the order.

When not all members of a class are initialized within an instantiation, a default value is inherited.
Those default values are specified in a <<ccsss-default-values, dedicated section>> below

NOTE: CartoSym-CSS supports and recommends the use of `{` `}` for object instances, and of `[` `]` for arrays,
for also supports `(` `)` in these contexts for compatibility with the CQL2-Text and WKT encodings.
A CQL2-Text expression (including WKT geometry) can therefore be used directly as an expression in a selector or symbolizer parameter value.
However, a CartoSym-CSS expression making use of the curly and/or square brackets will not be a valid CQL2 expression.

===== Tuples and related implications

The concept of a tuple is introduced, corresponding to the CQL2-Text Well-Known Text (WKT) coordinates in the above polygon examples.
Based on the logical model, each of those tuples actually correspond to a Point instance.
In order to maintain consistency with the CQL2-Text WKT encoding, the logical model as well as the object instance encodings,
a number of alternative encoding rules need to be established.
A tuple must be able to replace either:

* an array of coordinate values,
* an instance of a class defining a single property being such an array (e.g., Point), or
* a class identified as being replaceable by a tuple.

Therefore, the following equivalent definitions are all valid where a POINT is expected:

* `POINT(30 10)` -- The standard WKT form where the tuple replaces the array of coordinates, implying the _coordinates_ member
* `POINT( (30, 10) )` -- Using an array of coordinates, implying the _coordinates_ member, using the CQL2 square brackets
* `POINT{ [30, 10] }` -- Using an array of coordinates, implying the _coordinates_ member, using the CartoSym-CSS square and curly brackets
* `POINT{coordinates: 30 10}` -- The tuple replacing the array of coordinates, explicit coordinates _member_
* `POINT{coordinates: [30, 10]}` -- Using an array of coordinates, explicit coordinates _member_
* `{30 10}` -- Implied class, tuple replacing array of coordinates, implied _coordinates_ member
* `{ [30, 10] }` -- Implied class, using array of coordinates, implied _coordinates_ member
* `{coordinates: 30 10}` -- Implied class, tuple replacing array of coordinates, explicit _coordinates_ member
* `{coordinates: [30, 10]}` -- Implied class, using an array of coordinates, explicit _coordinates_ member
* `30 10`  -- Implied class, tuple replacing Point instance

The following are some equivalent examples of valid definitions where a polygon is expected:

* `POLYGON( (0 40, 10 40, 10 50, 0 50, 0 40) )`
* `POLYGON( (
   POINT(0 40),
   POINT(10 40),
   POINT(10 50),
   POINT(0 50),
   POINT(0 40)
  ) )`
* `POLYGON( (
   POINT( (0, 40) ),
   POINT( (10, 40) ),
   POINT( (10, 50) ),
   POINT( (0, 50) ),
   POINT( (0, 40) )
  ) )`
* `POLYGON( (
   POINT(coordinates: (0, 40)),
   POINT(coordinates: (10, 40)),
   POINT(coordinates: (10, 50)),
   POINT(coordinates: (0, 50)),
   POINT(coordinates: (0, 40))
  ) )`
* `POLYGON( (
   POINT(coordinates: 0 40),
   POINT(coordinates: 10 40),
   POINT(coordinates: 10 50),
   POINT(coordinates: 0 50),
   POINT(coordinates: 0 40)
  ) )`

The element of tuples can be either numeric literals or identifiers.

The classes defined in this Standard that can be encoded as tuples are:

* _Point_ (from WKT)
* _UnitPoint_ (defining only coordinate values),
* _TextAlignment_ (defining a horizontal and vertical alignment),
* _Color_ (defining red, green and blue components),
* _ValueColor_ (defining a value and color -- note that the color itself can be a tuple),
* _ValueOpacity_ (defining a value and an opacity,
* _Quaternion_ (defining w, x, y, z components),
* _Vector3D_ and _FloatVector3D_ (defining x, y, z components) -- NOTE: Change to UnitPoint3D?.

The tuple syntax can also be used to specify the _dashPattern_ array of dashed strokes.

The following are equivalent example definitions where a _UnitPoint_ is expected allowing each coordinate to be qualified with a unit of measure:

* `50 pc 50 pc`
* `UnitPoint(x: 50 pc; y: 50 pc;)`
* `UnitPoint(x: 50 pc, y: 50 pc)`
* `{50 pc, 50 pc}`

The following are equivalent example definitions where a _TextAligment_ is expected:

* `left top`
* `TextAlignment(left, top)`
* `TextAlignment(horizontal: left; vertical: top)`
* `{left, top}`

===== Units of measure

The following abbreviations are used, following a value, to qualify it with a unit of measure.
These are mainly used for _UnitPoint_ coordinates, as well as with distance value such as those specified for Shape graphics e.g., the radius of a circle.

.Units of measure abbreviations
[width="90%",options="header"]
|===
| Unit         |Abbreviation   | Notes
| pixels       | px            | Display unit; not dependent on display resolution
| meters       | m             | Real-world unit (SI unit of length)
| feet         | ft            | Real-world unit (0.3048 m)
| percent      | pc            | Relative value whose meaning depends on context e.g., Image's _hotSpot_, _scaling_.
| points       | pt            | One point is equal to 1/72 inch (0.3528 mm).
| em           | em            | One em is equal to the target's selected or default font point size.
| screenInches | inch          | Display unit (25.4 mm); see http://docs.ogc.org/DRAFTS/20-058.html#rc_display-resolution[OGC _API - Maps_ "Display Resolution" requirements class] (`mm-per-pixel`) which defaults to 0.28 mm/pixel (~90.7142857 pixels/inch).
| screenCM     | cm            | Display unit (10 mm); see http://docs.ogc.org/DRAFTS/20-058.html#rc_display-resolution[OGC _API - Maps_ "Display Resolution" requirements class] (`mm-per-pixel`) which defaults to 0.28 mm/pixel (0.028 cm/pixel).
| screenMM     | mm            | Display unit; see http://docs.ogc.org/DRAFTS/20-058.html#rc_display-resolution[OGC _API - Maps_ "Display Resolution" requirements class] (`mm-per-pixel`) which defaults to 0.28 mm/pixel.
| (none)       |               | For relative values like scaling, 100 times less than if _pc_ is specified. For screen-space objects, defaults to pixels.
|===

===== Conditional expressions

As an extension to CQL2-Text, this encoding adds support for conditional expressions using the grammar:

<if-expression> '`?`' <then-expression> '`:`' <else-expression>

===== Enumeration values

As an extension to CQL2-Text, this encoding supports the concept of enumeration values, which do not need to be enclosed in single quotes.
For compatibility with CQL2, the same identifier enclosed within single quotes is considered equivalent.

Enumeration values must conform to the CQL2 _identifier_ grammar production rule, but may not be enclosed within double-quotes.

In a context where an enumeration is expected, the enumeration value takes precedence over an identifier that may be resolved by the same name.
In order to explicitly refer to the identifier, the identifier can be enclosed in double-quotes.

===== Colors

Color values can be expressed using any of the forms allowed for instantiations, or using a tuple:

* `Color(255, 100, 50)`
* `Color{255, 100, 50}`
* `Color(r: 255, g: 100, b: 50)`
* `Color{r: 255, g: 100, b: 50}`
* `{255, 100, 50}`
* `{r: 255; g: 100; b: 50;}`
* `255 100 50`

Colors can also be expressed as a hexadecimal value prefixed by a `#` symbol, as in Web CSS:

* `#FF6432`

Finally, colors can also be expressed as an enumeration value for https://www.w3.org/wiki/CSS/Properties/color/keywords[named web colors]:

* `red`
* `'red'`

.Named web color enumeration
[width="90%",options="header"]
|===
|  Name                |   Hexadecimal |Value (r, g, b)
|  black               |    `0x000000` |   0,   0,   0 |
   dimGray             |    `0x696969` | 105, 105, 105 |
   dimGrey             |    `0x696969` | 105, 105, 105 |
   gray                |    `0x808080` | 128, 128, 128 |
   grey                |    `0x808080` | 128, 128, 128 |
   darkGray            |    `0xa9a9a9` | 169, 169, 165 |
   darkGrey            |    `0xa9a9a9` | 169, 169, 165 |
   silver              |    `0xc0c0c0` | 192, 192, 192 |
   lightGray           |    `0xd3d3d3` | 211, 211, 211 |
   lightGrey           |    `0xd3d3d3` | 211, 211, 211 |
   gainsboro           |    `0xdcdcdc` | 220, 220, 220 |
   whiteSmoke          |    `0xf5f5f5` | 245, 245, 245 |
   white               |    `0xffffff` | 255, 255, 255 |
   rosyBrown           |    `0xbc8f8f` | 188, 143, 143 |
   indianRed           |    `0xcd5c5c` | 205,  92,  92 |
   brown               |    `0xa52a2a` | 165,  42,  42 |
   fireBrick           |    `0xb22222` | 178,  34,  34 |
   lightCoral          |    `0xf08080` | 240, 128, 128 |
   maroon              |    `0x800000` | 128,   0,   0 |
   darkRed             |    `0x8b0000` | 139,   0,   0 |
   red                 |    `0xff0000` | 255,   0,   0 |
   snow                |    `0xfffafa` | 255, 250, 250 |
   mistyRose           |    `0xffe4e1` | 255, 228, 225 |
   salmon              |    `0xfa8072` | 250, 128, 114 |
   tomato              |    `0xff6347` | 255,  99,  71 |
   darkSalmon          |    `0xe9967a` | 233, 150, 122 |
   coral               |    `0xff7f50` | 255, 127,  80 |
   orangeRed           |    `0xff4500` | 255,  69,   0 |
   lightSalmon         |    `0xffa07a` | 255, 160, 122 |
   sienna              |    `0xa0522d` | 160,  82,  45 |
   seaShell            |    `0xfff5ee` | 255, 245, 238 |
   chocolate           |    `0xd2691e` | 210, 105,  30 |
   saddleBrown         |    `0x8b4513` | 139,  69,  19 |
   sandyBrown          |    `0xf4a460` | 244, 164,  96 |
   peachPuff           |    `0xffdab9` | 255, 218, 185 |
   peru                |    `0xcd853f` | 205, 133,  63 |
   linen               |    `0xfaf0e6` | 250, 240, 230 |
   bisque              |    `0xffe4c4` | 255, 228, 196 |
   darkOrange          |    `0xff8c00` | 255, 140,   0 |
   burlyWood           |    `0xdeb887` | 222, 184, 135 |
   tan                 |    `0xd2b48c` | 210, 180, 140 |
   antiqueWhite        |    `0xfaebd7` | 250, 235, 215 |
   navajoWhite         |    `0xffdead` | 255, 222, 173 |
   blanchedAlmond      |    `0xffebcd` | 255, 235, 205 |
   papayaWhip          |    `0xffefd5` | 255, 239, 213 |
   moccasin            |    `0xffe4b5` | 255, 228, 181 |
   orange              |    `0xffa500` | 255, 165,   0 |
   wheat               |    `0xf5deb3` | 245, 222, 179 |
   oldLace             |    `0xfdf5e6` | 253, 245, 230 |
   floralWhite         |    `0xfffaf0` | 255, 250, 240 |
   darkGoldenrod       |    `0xb8860b` | 184, 134,  11 |
   goldenrod           |    `0xdaa520` | 218, 165,  32 |
   cornsilk            |    `0xfff8dc` | 255, 248, 220 |
   gold                |    `0xffd700` | 255, 215,   0 |
   khaki               |    `0xf0e68c` | 240, 230, 140 |
   lemonChiffon        |    `0xfffacd` | 255, 250, 205 |
   paleGoldenrod       |    `0xeee8aa` | 238, 232, 170 |
   darkKhaki           |    `0xbdb76b` | 189, 183, 107 |
   beige               |    `0xf5f5dc` | 245, 245, 220 |
   lightGoldenRodYellow|    `0xfafad2` | 250, 250, 210 |
   olive               |    `0x808000` | 128, 128,   0 |
   yellow              |    `0xffff00` | 255, 255,   0 |
   lightYellow         |    `0xffffe0` | 255, 255, 224 |
   ivory               |    `0xfffff0` | 255, 255, 240 |
   oliveDrab           |    `0x6b8e23` | 107, 142,  35 |
   yellowGreen         |    `0x9acd32` | 154, 205,  50 |
   darkOliveGreen      |    `0x556b2f` |  85, 107,  47 |
   greenYellow         |    `0xadff2f` | 173, 255,  47 |
   chartreuse          |    `0x7fff00` | 127, 255,   0 |
   lawnGreen           |    `0x7cfc00` | 124, 252,   0 |
   darkSeaGreen        |    `0x8fbc8f` | 143, 188, 139 |
   forestGreen         |    `0x228b22` |  34, 139,  34 |
   limeGreen           |    `0x32cd32` |  50, 205,  50 |
   lightGreen          |    `0x90ee90` | 144, 238, 144 |
   paleGreen           |    `0x98fb98` | 152, 251, 152 |
   darkGreen           |    `0x006400` |   0, 100,   0 |
   green               |    `0x008000` |   0, 128,   0 |
   lime                |    `0x00ff00` |   0, 255,   0 |
   honeyDew            |    `0xf0fff0` | 240, 255, 240 |
   seaGreen            |    `0x2e8b57` |  46, 139,  87 |
   mediumSeaGreen      |    `0x3cb371` |  60, 179, 113 |
   springGreen         |    `0x00ff7f` |   0, 255, 127 |
   mintCream           |    `0xf5fffa` | 245, 255, 250 |
   mediumSpringGreen   |    `0x00fa9a` |   0, 250, 154 |
   mediumAquaMarine    |    `0x66cdaa` | 102, 205, 170 |
   aquamarine          |    `0x7fffd4` | 127, 255, 212 |
   turquoise           |    `0x40e0d0` |  64, 224, 208 |
   lightSeaGreen       |    `0x20b2aa` |  32, 178, 170 |
   mediumTurquoise     |    `0x48d1cc` |  72, 209, 204 |
   darkSlateGray       |    `0x2f4f4f` |  47,  79,  79 |
   darkSlateGrey       |    `0x2f4f4f` |  47,  79,  79 |
   paleTurquoise       |    `0xafeeee` | 175, 238, 238 |
   teal                |    `0x008080` |   0, 128, 128 |
   darkCyan            |    `0x008b8b` |   0, 139, 139 |
   aqua                |    `0x00ffff` |   0, 255, 255 |
   cyan                |    `0x00ffff` |   0, 255, 255 |
   lightCyan           |    `0xe0ffff` | 224, 255, 255 |
   azure               |    `0xf0ffff` | 240, 255, 255 |
   darkTurquoise       |    `0x00ced1` |   0, 206, 209 |
   cadetBlue           |    `0x5f9ea0` |  95, 158, 160 |
   powderBlue          |    `0xb0e0e6` | 176, 224, 230 |
   lightBlue           |    `0xadd8e6` | 173, 216, 230 |
   deepSkyBlue         |    `0x00bfff` |   0, 191, 255 |
   skyBlue             |    `0x87ceeb` | 135, 206, 235 |
   lightSkyBlue        |    `0x87cefa` | 135, 206, 250 |
   steelBlue           |    `0x4682b4` |  70, 130, 180 |
   aliceBlue           |    `0xf0f8ff` | 240, 248, 255 |
   dodgerBlue          |    `0x1e90ff` |  30, 144, 255 |
   slateGray           |    `0x708090` | 112, 128, 144 |
   slateGrey           |    `0x708090` | 112, 128, 144 |
   lightSlateGray      |    `0x778899` | 119, 136, 153 |
   lightSlateGrey      |    `0x778899` | 119, 136, 153 |
   lightSteelBlue      |    `0xb0c4de` | 176, 196, 222 |
   cornflowerBlue      |    `0x6495ed` | 100, 149, 237 |
   royalBlue           |    `0x4169e1` |  65, 105, 225 |
   midnightBlue        |    `0x191970` |  25,  25, 112 |
   lavender            |    `0xe6e6fa` | 230, 230, 250 |
   navy                |    `0x000080` |   0,   0, 128 |
   darkBlue            |    `0x00008b` |   0,   0, 139 |
   mediumBlue          |    `0x0000cd` |   0,   0, 205 |
   blue                |    `0x0000ff` |   0,   0, 255 |
   ghostWhite          |    `0xf8f8ff` | 248, 248, 255 |
   slateBlue           |    `0x6a5acd` | 106,  90, 205 |
   darkSlateBlue       |    `0x483d8b` |  72,  61, 139 |
   mediumSlateBlue     |    `0x7b68ee` | 123, 104, 238 |
   mediumPurple        |    `0x9370db` | 147, 112, 219 |
   blueViolet          |    `0x8a2be2` | 138,  43, 226 |
   indigo              |    `0x4b0082` |  75,   0, 130 |
   darkOrchid          |    `0x9932cc` | 153,  50, 204 |
   darkViolet          |    `0x9400d3` | 148,   0, 211 |
   mediumOrchid        |    `0xba55d3` | 186,  85, 211 |
   thistle             |    `0xd8bfd8` | 216, 191, 216 |
   plum                |    `0xdda0dd` | 221, 160, 221 |
   violet              |    `0x40e0d0` | 238, 130, 238 |
   purple              |    `0x800080` | 128,   0, 128 |
   darkMagenta         |    `0x8b008b` | 139,   0, 139 |
   magenta             |    `0xff00ff` | 255,   0, 255 |
   fuschia             |    `0xff00ff` | 255,   0, 255 |
   orchid              |    `0xda70d6` | 218, 112, 214 |
   mediumVioletRed     |    `0xc71585` | 199,  21, 133 |
   deepPink            |    `0xff1493` | 255,  20, 147 |
   hotPink             |    `0xff69b4` | 255, 155, 180 |
   lavenderBlush       |    `0xfff0f5` | 255, 240, 245 |
   paleVioletRed       |    `0xdb7093` | 219, 112, 147 |
   crimson             |    `0xdc143c` | 220,  20,  60 |
   pink                |    `0xffc0cb` | 255, 192, 203 |
   lightPink           |    `0xffb6c1` | 255, 182, 193
|===

==== Examples

.CCSSS Example encoding style using "Core" requirements class
====
[source,ccsss]
----
include::../examples/1-core.cscss[]
----
====

===== Basic Vector Styling

.CCSSS Example encoding style for polygon features using "Basic Vector Styling" requirements class
====
[source,ccsss]
----
include::../examples/2-vector-polygon.cscss[]
----
====

.CCSSS Example encoding style for line features using "Basic Vector Styling" requirements class
====
[source,ccsss]
----
include::../examples/3-vector-line.cscss[]
----
====

.CCSSS Example encoding style for point features using "Basic Vector Styling" requirements class
====
[source,ccsss]
----
include::../examples/4-vector-point.cscss[]
----
====

===== Basic Coverage Styling

.CCSSS Example encoding style rendering DEM with a color map using "Basic Coverage Styling" requirements class
====
[source,ccsss]
----
include::../examples/5-coverage-dem.cscss[]
----
====

.CCSSS Example encoding style rendering sentinel-2 in natural color from 3 bands using "Basic Coverage Styling" requirements class
====
[source,ccsss]
----
include::../examples/6-coverage-sentinel2.cscss[]
----
====

===== Arithmetic Operations (with Basic Coverage Styling)

.CCSSS Example encoding style rendering NDVI with color map using "Basic Coverage Styling" requirements class
====
[source,ccsss]
----
include::../examples/7-coverage-ndvi.cscss[]
----
====

===== Hill Shading

.CCSSS Example encoding style rendering DEM with hill-shading and a color map using "Basic Coverage Styling" and "Hill Shading" requirements classes
====
[source,ccsss]
----
include::../examples/8-coverage-hillshading.cscss[]
----
====

.CCSSS Example encoding style rendering DEM with hill-shading using an opacity and shading intensity color map using "Basic Coverage Styling" and "Hill Shading" requirements classes
====
[source,ccsss]
----
include::../examples/9-coverage-hillshading-opacity.cscss[]
----
====

==== BNF token definitions

The following token definitions for ANTLR4 can be used to generate a lexer for the encoding.

[source,options="unnumbered"]
----
include::../schemas/CartoSym-CSS-Lexer.g4[]
----

==== BNF grammar definition

The following grammar for ANTLR4 can be used to generate a parser for the encoding.

[source,options="unnumbered"]
----
include::../schemas/CartoSym-CSS-Grammar.g4[]
----

=== Requirements

include::../requirements/rc-ccsss-encoding.adoc[]
