
[[rc_table-coverage]]

[requirements_class]
.Basic Coverage Styling
====
[%metadata]
identifier:: http://www.opengis.net/spec/symbology-1/2.0/req/coverage
inherit:: http://www.opengis.net/spec/symbology-1/2.0/req/core
subject:: Style encodings and Renderers
====

[[req-coverage-color-channels]]

===== Symbolizer `colorChannels` property

[requirement]
====
[%metadata]
identifier:: /req/coverage/color-channels
part:: An Encoding SHALL support defining a `colorChannels` Symbolizer property as a Color object.
part:: A Renderer SHALL support ...
====

===== Symbolizer `alphaChannel` property

[requirement]
====
[%metadata]
identifier:: /req/coverage/alpha-channel
part:: An Encoding SHALL support defining a `alphaChannel` Symbolizer property as a float.
part:: A Renderer SHALL support ...
====

===== Symbolizer `singleChannel` property

[requirement]
====
[%metadata]
identifier:: /req/coverage/single-channel
part:: An Encoding SHALL support defining a `singleChannel` Symbolizer property as a float.
part:: A Renderer SHALL support ...
====


===== Symbolizer `colorMap` property

[requirement]
====
[%metadata]
identifier:: /req/coverage/color-map
part:: An Encoding SHALL support defining a `colorMap` Symbolizer property as an array of `value` (float) and `color` (Color) pairs which can be tagged with a `name`.
part:: A Renderer SHALL support ...
====

===== Symbolizer `opacityMap` property

[requirement]
====
[%metadata]
identifier:: /req/coverage/opacity-map
part:: An Encoding SHALL support defining a `opacityMap` Symbolizer property as an array of `value` (float) and `opacity` (float) pairs which can be tagged with a `name`.
part:: A Renderer SHALL support ...
====
