
[[rc_table-core]]

[requirements_class]
.Core
====
[%metadata]
identifier:: http://www.opengis.net/spec/symbology-1/2.0/req/core
subject:: Style encodings and Renderers
====

[[req-core-rules]]
==== Requirement for Style `stylingRules` property

[requirement]
====
[%metadata]
identifier:: /req/core/rules
part:: An Encoding SHALL support individually storing and preserving the order of each StylingRule constituting a Style.
part:: A Renderer SHALL support considering in order each individual StylingRule constituting a style.
part:: The Symbolizer properties specified in a StylingRule appearing later in a Style's list of rules and whose Selector
evaluates to true SHALL be interpreted as overriding all Symbolizer properties set by earlier rules.
====

[[req-core-nested]]
==== Requirement for StylingRule `nestedRules` property

[requirement]
====
[%metadata]
identifier:: /req/core/nested
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-expressions]]
==== Requirement for identifier expressions

[requirement]
====
[%metadata]
identifier:: /req/core/expressions
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-selector]]
==== Requirement for StylingRule `selector` property

[requirement]
====
[%metadata]
identifier:: /req/core/selector
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-symbolizer]]
==== Requirement for StylingRule `symbolizer` property

[requirement]
====
[%metadata]
identifier:: /req/core/symbolizer
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-parameters]]
==== Requirement for setting Symbolizer properties parameter values

[requirement]
====
[%metadata]
identifier:: /req/core/parameters
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-visibility]]
==== Requirement for Symbolizer `visibility` property

[requirement]
====
[%metadata]
identifier:: /req/core/visibility
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====

[[req-core-opacity]]
==== Requirement for Symbolizer `opacity` property

[requirement]
====
[%metadata]
identifier:: /req/core/opacity
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-zorder]]
==== Requirement for Symbolizer `zOrder` property

[requirement]
====
[%metadata]
identifier:: /req/core/zorder
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-literals]]
==== Requirement for literal expressions

[requirement]
====
[%metadata]
identifier:: /req/core/literals
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-identifiers]]
==== Requirement for identifier expressions

[requirement]
====
[%metadata]
identifier:: /req/core/identifiers
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-scale]]
==== Requirement for a visualization scale denominator system identifiers

[requirement]
====
[%metadata]
identifier:: /req/core/scale
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-time]]
==== Requirement for visualization time system identifiers

[requirement]
====
[%metadata]
identifier:: /req/core/time
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-layers]]
==== Requirement for data layer system identifiers

[requirement]
====
[%metadata]
identifier:: /req/core/layers
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-logical]]
==== Requirement for logical operation expressions

[requirement]
====
[%metadata]
identifier:: /req/core/logical
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-relational]]
==== Requirement for relational operation expressions

[requirement]
====
[%metadata]
identifier:: /req/core/relational
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-arrays]]
==== Requirement for array expressions

[requirement]
====
[%metadata]
identifier:: /req/core/arrays
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====


[[req-core-instances]]
==== Requirement for instance expressions

[requirement]
====
[%metadata]
identifier:: /req/core/instances
part:: An Encoding SHALL support ...
part:: A Renderer SHALL support ...
====
