[appendix,obligation="informative"]
[[annex-sldse]]
== Mapping of SLD/SE and notable vendor extensions to the Conceptual Model

This annex maps constructs of the OGC Styled Layer Descriptor (SLD) and Symbology Encoding (SE) 1.1
to the conceptual model and requirements classes defined in the Part 1 of this Standard, with the goal of facilitating
conformance to this Standard for Rendering engines based on SLD/SE and writing conversion tools
that can convert in either or both direction between SLD/SE and the two encodings defined in this
Standard.

=== Requirements Class "Core"

.Mapping of the "Core" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct         | SE Equivalent
| *Styling Rules*   | `<Rule>`
| name              | `<Name>` inside `<Rule>`
| symbolizer        | `<PointSymbolizer>`, `<LineSymbolizer>`, `<PolygonSymbolizer>`, `<TextSymbolizer>`, `<RasterSymbolizer>`
| Selector          | `<ogc:Filter>`
| nestedRules       | `<ogc:ElseFilter>` provides limited support for one use case of nested rules 

| *Literal Expression* | `<ogc:Literal>`
| TextLiteral       | text directly in `<ogc:Literal>`
| BoolLiteral       | true or false in `<ogc:Literal>`
| NullLiteral       | `<PropertyIsNull>` when testing for null values
| IntegerLiteral    | integer value directly in `<ogc:Literal>`
| RealLiteral       | double value inside `<ogc:Literal>`
| ArrayLiteral      | N/A
| InstanceLiteral   | N/A

| *Expression*         | 
| FunctionExpression   | `<ogc:Function>`
| IdentifierExpression | `<ogc:PropertyName>` for feature properties, `<SourceChannelName>` for raster fields
| InstanceExpression   | N/A
| ArrayExpression      | N/A

| *Core Logic and Relational Operators* | 
| Relational Operator  | Comparison operators (`<ogc:PropertyIsEqualTo>`, `<ogc:PropertyIsLessThan>`, etc.)
| LogicOperator        | Logical operators (`<ogc:And>`, `<ogc:Or>`, `<ogc:Not>`)
|===

.Mapping of the "Sytem Identifiers Expressions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                      | SE Equivalent
| visualization                  | N/A
| visualization.scaleDenominator | `<MaxScaleDenominator>`, `<MinScaleDenominator>`
| visualization.dateTime         | N/A
| visualization.date             | N/A
| visualization.timeOfDay        | N/A
| visualization.pass             | 
| feature.pass                   | 
| dataLayer                      | N/A
| dataLayer.identifier           | `<NamedLayer>` and `<Name>`
| dataLayer.type                 | N/A
|===

.SLD Example encoding style using "Core" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Core</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <ogc:Filter>
                  <ogc:PropertyIsEqualTo>
                     <ogc:PropertyName>landuse</ogc:PropertyName>
                     <ogc:Literal>parking</ogc:Literal>
                  </ogc:PropertyIsEqualTo>
               </ogc:Filter>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">#FF0000</CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
                  <stroke>
                     <CssParameter name="stroke">#000000</CssParameter>
                     <CssParameter name="stroke-width">1</CssParameter>
                  </stroke>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
<StyledLayerDescriptor>
----
====

=== Requirements Class "Parameter Values"

.SLD Example encoding style using "Parameter Values" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
  <NamedLayer>
    <Name>Landuse</Name>
    <UserStyle>
      <Name>Styling a land use layer</Name>
      <Title>Styling a land use layer</Title>
      <Abstract>Styling land use data with Style &amp; Symbology Parameter Values</Abstract>
      <FeatureTypeStyle>
        <Rule>
          <Name>parking</Name>
          <Filter>
            <PropertyIsEqualTo>
              <PropertyName>landuse</PropertyName>
              <Literal>parking</Literal>
            </PropertyIsEqualTo>
          </Filter>
          <MaxScaleDenominator>200000</MaxScaleDenominator>
          <PolygonSymbolizer>
            <Fill>
              <CssParameter name="fill">#ff0000</CssParameter>
            </Fill>
            <Stroke>
              <CssParameter name="stroke">#000000</CssParameter>
              <CssParameter name="stroke-width">1</CssParameter>
            </Stroke>
          </PolygonSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Basic Vector Features Styling"

.Mapping of the "Basic Vector Features Styling" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                   | SE Equivalent
| Text                        | `<TextSymbolizer>`
| Font                        | <Font>` with `<SvgParameter name="font-family">`, `<SvgParameter name="font-size">`, `<SvgParameter name="font-style">`, `<SvgParameter name="font-weight">`
| TextAlignment               | `<TextSymbolizer>`
| HAlignment                  | `<TextSymbolizer>`
| VAlignment                  | `<TextSymbolizer>`
| Image                       | `<Graphic>`
| Dot                         | `<PointSymbolizer>`
| Marker                      | `<Graphic>`
| GraphicalUnit               | N/A
| Stroke                      | `<Stroke>`
| Fill                        | `<Fill>`
| Color                       | `<CssParameter>`
|===


.SLD Example encoding style using "Basic Vector Features Styling" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
  <NamedLayer>
    <Name>Landuse</Name>
    <UserStyle>
      <Name>Styling a land use layer</Name>
      <Title>Styling a land use layer</Title>
      <Abstract>Styling land use data with Style &amp; Symbology Parameter Values</Abstract>
      <FeatureTypeStyle>
        <Rule>
          <Name>parking</Name>
          <Filter>
            <PropertyIsEqualTo>
              <PropertyName>landuse</PropertyName>
              <Literal>parking</Literal>
            </PropertyIsEqualTo>
          </Filter>
          <MaxScaleDenominator>200000</MaxScaleDenominator>
          <PointSymbolizer>
            <Graphic>
              <ExternalGraphic>
                <OnlineResource xlink:type="simple" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Parking_icon.svg/128px-Parking_icon.svg.png"/>
              </ExternalGraphic>
            </Graphic>
          </PointSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Basic Coverage Styling"

.Mapping of the "Basic Coverage Styling" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| ColorChannels                | `<ChannelSelection>` with `<RedChannel>`, `<GreenChannel>`, `<BlueChannel>` or `<GrayChannel>`
| AlphaChannel                 | N/A
| SingleChannel                | `<ChannelSelection>` with `<RedChannel>`, `<GreenChannel>`, `<BlueChannel>` or `<GrayChannel>` 
| ColorMap                     | `<ColorMap>`
| OpacityMap                   | `<Opacity>`
| ValueColor                   | `<ColorMapEntry>`
| ValueOpacity                 | `<ColorMapEntry>`

|*Hill Shading*                |
| Construct                    | SE Equivalent
| AzimuthElevation             | `<ogc:Function>` with <ogc:PropertyName> and `<ogc:Literal>`
| HillShading                  | `<ogc:Function>` with <ogc:PropertyName> and `<ogc:Literal>`
| Symbolizer                   | `<RasterSymbolizer>`

|*Contrast Enhancement*        |
| contrastEnhancement          | `<ContrastEnhancement>`
|===

.SLD Example encoding style rendering DEM with a color map using "Basic Coverage Styling" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.1.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
   <NamedLayer>
      <Name>Elevation</Name>
      <UserStyle>
         <Name>DEM with color map</Name>
         <Abstract>Applying a color map to a Digital Elevation Model with Style &amp; Symbology Basic Coverage Styling</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>DEM with color map</Name>
               <Title>DEM with color map</Title>
               <MaxScaleDenominator>200000</MaxScaleDenominator>
               <sld:RasterSymbolizer>
                  <sld:Opacity>0.8</sld:Opacity>
                  <sld:ChannelSelection>
                     <sld:GrayChannel>
                        <sld:SourceChannelName>elevation</sld:SourceChannelName>
                     </sld:GrayChannel>
                  </sld:ChannelSelection>
                  <sld:ColorMap>
                     <sld:ColorMapEntry color="#608849" quantity="0" label="0"/>
                     <sld:ColorMapEntry color="#E2DBA7" quantity="900" label="900"/>
                     <sld:ColorMapEntry color="#FCC575" quantity="1300" label="1300"/>
                     <sld:ColorMapEntry color="#FCA886" quantity="1900" label="1900"/>
                     <sld:ColorMapEntry color="#FAFAFA" quantity="2500" label="2500"/>
                  </sld:ColorMap>
               </sld:RasterSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Basic Labeling"

.Mapping of the "Basic Labeling" & "Font Outlines" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SLD Equivalent
| Label                        | `<TextSymbolizer>` with `<Label>`
| LabelPlacement               | `<LabelPlacement>`
| ImageOutline                 | `<Graphic>`
| Font                         | `<Font>` with `<SvgParameter name="font-family">`, `<SvgParameter name="font-size">`, `<SvgParameter name="font-style">`, `<SvgParameter name="font-weight">`
| FontOutline                  | `<Halo>`
|===

.SLD Example encoding style using "Basic Labeling" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<StyledLayerDescriptor version="1.1.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:se="http://www.opengis.net/se">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Basic Labeling</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <TextSymbolizer>
                <Label>
                  <ogc:PropertyName>name</ogc:PropertyName>
                </Label>
                <Font>
                  <CssParameter name="font-family">Arial</CssParameter>
                  <CssParameter name="font-size">12</CssParameter>
                  <CssParameter name="font-style">normal</CssParameter>
                  <CssParameter name="font-weight">bold</CssParameter>
                </Font>
                <LabelPlacement>
                  <PointPlacement>
                    <AnchorPoint>
                      <AnchorPointX>0.5</AnchorPointX>
                      <AnchorPointY>0.0</AnchorPointY>
                    </AnchorPoint>
                    <Displacement>
                      <DisplacementX>0</DisplacementX>
                      <DisplacementY>25</DisplacementY>
                    </Displacement>
                    <Rotation>-45</Rotation>
                  </PointPlacement>
                </LabelPlacement>
                <Fill>
                  <CssParameter name="fill">#990099</CssParameter>
                </Fill>
               </TextSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Dashes"

.Mapping of the "Dashes" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| dashPattern                  | GraphicStroke with GraphicStrokeType and Graphic
| dashOffset                   | `<SvgParameter name="stroke-dashoffset">` with `<ogc:Literal>`
|===

.SLD Example encoding style using "Dashes" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Dashes</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <LineSymbolizer>
                  <Stroke>
                     <CssParameter name="stroke">#000000</CssParameter>
                     <CssParameter name="stroke-width">1</CssParameter>
                     <CssParameter name="stroke-dasharray">5 2 1 2</CssParameter>
                     <CssParameter name="stroke-dashoffset">2</CssParameter>
                  </Stroke>
               </LineSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Casing and Centerline"

.Mapping of the "Casing and Centerline" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| casing                       | `<Stroke>`
| center                       | `<Stroke>`
|===

.SLD Example encoding style using "Casing and Centerline" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Casing and Centerline</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <LineSymbolizer>
                  <Stroke>
                     <CssParameter name="stroke">#000000</CssParameter>
                     <CssParameter name="stroke-width">1</CssParameter>
                  </Stroke>
                  <Stroke>
                     <CssParameter name="stroke">#FFFFFF</CssParameter>
                     <CssParameter name="stroke-width">3</CssParameter>
                  </Stroke>
               </LineSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Hatch fills"

.Mapping of the "Hatch fills" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| HatchStyle                   | `<GraphicFill>` with `<Graphic>` & `<Mark>` and CssParameter such as stroke, stroke-width etc
|===

.SLD Example encoding style using "Hatch fills" requirements class
====
[source,sld]
----
?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor
xmlns="http://www.opengis.net/sld"
xmlns:sld="http://www.opengis.net/sld"
xmlns:ogc="http://www.opengis.net/ogc"
xmlns:gml="http://www.opengis.net/gml"
xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0.0">
  <NamedLayer>
    <UserStyle>
      <Name>tl 2010 08013 arealm</Name>
      <Title/>
      <FeatureTypeStyle>
        <Rule>
          <Name>cemeteries</Name>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>MTFCC</ogc:PropertyName>
              <ogc:Literal>K2582</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <MaxScaleDenominator>500000.0</MaxScaleDenominator>
          <sld:PolygonSymbolizer>
            <Fill>
              <GraphicFill>
                <Graphic>
                  <Mark>
                    <WellKnownName>shape://times</WellKnownName>
                    <Fill/>
                    <Stroke>
                      <CssParameter name="stroke">#ADD8E6</CssParameter>
                      <CssParameter name="stroke-width">1.0</CssParameter>
                    </Stroke>
                  </Mark>
                </Graphic>
              </GraphicFill>
            </Fill>
          </sld:PolygonSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Stipple fills"

.Mapping of the "Stipple fills" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| StippleStyle                 | `<GraphicFill>` with `<Graphic>` & `<Mark>` and CssParameter such as stroke, stroke-width etc
|===

.SLD Example encoding style using "Stipple fills" requirements class
====
[source,sld]
----
?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor
xmlns="http://www.opengis.net/sld"
xmlns:sld="http://www.opengis.net/sld"
xmlns:ogc="http://www.opengis.net/ogc"
xmlns:gml="http://www.opengis.net/gml"
xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0.0">
  <NamedLayer>
    <UserStyle>
      <Name>tl 2010 08013 arealm</Name>
      <Title/>
      <FeatureTypeStyle>
        <Rule>
          <Name>cemeteries</Name>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>MTFCC</ogc:PropertyName>
              <ogc:Literal>K2582</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <MaxScaleDenominator>500000.0</MaxScaleDenominator>
          <sld:PolygonSymbolizer>
            <Fill>
              <GraphicFill>
                <Graphic>
                  <sld:ExternalGraphic>
                    <sld:OnlineResource
                    xlink:type="simple"
                    xlink:href="./img/landmarks/area/grave_yard.png" />
                    <sld:Format>image/png</sld:Format>
                  </sld:ExternalGraphic>
                </Graphic>
              </GraphicFill>
            </Fill>
          </sld:PolygonSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
----
====

// === Requirements Class "Symbolizer Parameter Value Expressions"
// Unnecessary, as the examples are already provided in the "Parameter Values" requirements class.

// === Requirements Class "Any right-hand operands"
// Unnecessary, as the examples are already provided in the "Core" requirements class.

=== Requirements Class "Conditional Expressions"

.Mapping of the "Conditional Expressions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SLD Equivalent
| condition                    | `<ogc:Function>`
| thenExp                      | `<ogc:Function>`
| elseExp                      | `<ogc:Function>`
|===

.SLD Example encoding style using "Conditional Expressions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Conditional Expressions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="if_then_else">
                           <ogc:Function name="PropertyIsEqualTo">
                              <ogc:PropertyName>landuse</ogc:PropertyName>
                              <ogc:Literal>parking</ogc:Literal>
                           </ogc:Function>
                           <ogc:Literal>#FF0000</ogc:Literal>
                           <ogc:Literal>#00FF00</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Variables"

.Mapping of the "Variables" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| VariableExpression           | `<ogc:PropertyName>`
|===

.SLD Example encoding style using "Variables" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Variables</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:PropertyName>landuse</ogc:PropertyName>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Arithmetic Operators"

.Mapping of the "Arithmetic Operators" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| ArithmeticOperator           | `<ogc:Function>`
| add                          | `<ogc:Function>`
| sub                          | `<ogc:Function>`
| mul                          | `<ogc:Function>`
| div                          | `<ogc:Function>`
| intDiv                       | N/A
| mod                          | N/A
| pow                          | N/A
|===

.SLD Example encoding style using "Arithmetic Operators" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Arithmetic Operators</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="add">
                           <ogc:PropertyName>landuse</ogc:PropertyName>
                           <ogc:Literal>parking</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Text Relation Operators"

.Mapping of the "Text Relation Operators" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                     | SE Equivalent
| TextRelationOperator          | `<ogc:Function>`
| like                          | `<ogc:Function>`
| notLike                       | `<ogc:Function>`
| contains                      | `<ogc:Function>`
| startsWith                    | `<ogc:Function>`
| endsWith                      | `<ogc:Function>`
| notContains                   | `<ogc:Function>`
| notStartsWith                 | `<ogc:Function>`
| notEndsWith                   | `<ogc:Function>`
| like                          | `<ogc:Function>`
| notLike                       | `<ogc:Function>`
| contains                      | `<ogc:Function>`
| startsWith                    | `<ogc:Function>`
| endsWith                      | `<ogc:Function>`
| notContains                   | `<ogc:Function>`
| notStartsWith                 | `<ogc:Function>`
| notEndsWith                   | `<ogc:Function>`
|===

.SLD Example encoding style using "Text Relation Operators" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Text Relation Operators</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="like">
                           <ogc:PropertyName>landuse</ogc:PropertyName>
                           <ogc:Literal>parking</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Function Expressions"

.Mapping of the "Function Expressions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| FunctionCallExpression       | `<ogc:Function>`
| Function                     | `<ogc:Function>`
| uri                          | `<ogc:Function>`
|===

.SLD Example encoding style using "Function Expressions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Function Expressions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="uri">
                           <ogc:Literal>http://www.opengis.net/ogc</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Math Functions"

.Mapping of the "Math Functions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| MathFunctions                | `<ogc:Function>`
| abs                          | N/A
| acos                         | N/A
| asin                         | N/A
| atan                         | N/A
| atan2                        | N/A
| ceil                         | N/A
| cos                          | N/A
| cosh                         | N/A
| exp                          | N/A
| floor                        | N/A
| log                          | N/A
| log10                        | N/A
| max                          | N/A
| min                          | N/A
| pow                          | N/A
| random                       | N/A
| rint                         | N/A
| round                        | N/A
| sin                          | N/A
| sinh                         | N/A
| sqrt                         | N/A
| tan                          | N/A
| tanh                         | N/A
|===

.SLD Example encoding style using "Math Functions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Math Functions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="round">
                           <ogc:PropertyName>surface</ogc:PropertyName>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Array Relation Functions"

.Mapping of the "Array Relation Functions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| ArrayRelationFunctions       | `<ogc:Function>`
| a_containedBy                | `<ogc:Function>`
| a_contains                   | `<ogc:Function>`
| a_equals                     | `<ogc:Function>`
| a_overlaps                   | `<ogc:Function>`
|===

.SLD Example encoding style using "Array Relation Functions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Array Relation Functions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <PolygonSymbolizer>
                  <Fill>
                     <CssParameter name="fill">
                        <ogc:Function name="a_containedBy">
                           <ogc:PropertyName>landuse</ogc:PropertyName>
                           <ogc:Literal>parking</ogc:Literal>
                        </ogc:Function>
                     </CssParameter>
                     <CssParameter name="fill-opacity">0.5</CssParameter>
                  </Fill>
               </PolygonSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====

=== Requirements Class "Text Manipulation Functions"

.Mapping of the "Text Manipulation Functions" requirements class to SLD/SE constructs
[width="90%",options="header"]
|===
| Construct                    | SE Equivalent
| TextManipulationFunctions    | `<ogc:Function>`
| caseInsensitize              | `<ogc:Function>`
| accentInsensitize            | `<ogc:Function>`
| lowerCase                    | `<ogc:Function>`
| upperCase                    | `<ogc:Function>`
| concatenate                  | `<ogc:Function>`
| substitute                   | `<ogc:Function>`
| format                       | `<ogc:Function>`
|===

.SLD Example encoding style using "Text Manipulation Functions" requirements class
====
[source,sld]
----
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.1.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ogr="http://www.opengis.net/ogr"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd">
   <NamedLayer>
      <Name>Landuse</Name>
      <UserStyle>
         <Name>Styling a land use layer</Name>
         <Abstract>Styling land use data with Style &amp; Symbology Text Manipulation Functions</Abstract>
         <FeatureTypeStyle>
            <Rule>
               <Name>parking</Name>
               <Title>parking</Title>
               <TextSymbolizer>
                  <Label>
                     <ogc:Function name="strCapitalize">
                        <ogc:PropertyName>landuse</ogc:PropertyName>
                     </ogc:Function>
                  </Label>
               </TextSymbolizer>
            </Rule>
         </FeatureTypeStyle>
      </UserStyle>
   </NamedLayer>
</StyledLayerDescriptor>
----
====
