== Requirements Classes for Functions

[[rc-functions]]
=== Requirements Class "Function Expressions"
==== Overview

This requirements class adds support for function call expressions.

===== Function call expressions

[#img-uml-class-functions]
.Functions UML Class Diagram
[plantuml, target=diagram-classes, format=png]
....
abstract class Expression

FunctionCallExpression --|> Expression
FunctionCallExpression : function: Function
FunctionCallExpression : arguments: Expression[0..*]
FunctionCallExpression *-- Function
FunctionCallExpression *-- Expression

Function : name: string
Function : parameters: map < string, type >
Function : returnType: type
....

.FunctionCallExpression class
[width="90%",options="header"]
|===
| Name      | Type       | Definition                 | multiplicity
| function  | Function   | Function to be called      | 1
| arguments | Expression | Arguments to the function  | 0..*
|===

.Function class
[width="90%",options="header"]
|===
| Name         | Type                 | Definition                 | multiplicity
| name         | string               | Name                       | 1
| parameters   | map < string, type > | Parameters                 | 1
| returnType   | type                 | Return type                | 1
|===

===== Standard functions

A standard function is a Function with a pre-determined set of parameters, return value and behavior that may be registered with a URI.
Requirements class in this section defines standard functions.

.Standard functions URI mapping
[width="90%",options="header"]
|===
| Key   | Value      | Definition
| uri   | Function   | A URI allows to identify standard functiona, even if identical function names are used in different encoding, extension or implementations for different behaviors.
|===

==== Requirements

include::../requirements/rc-functions.adoc[]

[[rc-math]]
=== Requirements Class "Math Functions"
==== Overview

[#img-uml-class-math-functions]
.Math Functions UML Diagram
[plantuml, target=diagram-classes, format=png]
....
interface MathFunctions
MathFunctions --|> Function : standard functions
MathFunctions : abs(x : double) double
MathFunctions : acos(x : double) double
MathFunctions : asin(x : double) double
MathFunctions : atan(x : double) double
MathFunctions : atan2(y : double, x : double) double
MathFunctions : ceil(x : double) double
MathFunctions : cos(x : double) double
MathFunctions : cosh(x : double) double
MathFunctions : exp(x : double) double
MathFunctions : floor(x : double) double
MathFunctions : log(x : double) double
MathFunctions : log10(x : double) double
MathFunctions : max(x : double, y : double) double
MathFunctions : min(x : double, y : double) double
MathFunctions : pow(x : double, y : double) double
MathFunctions : random() double
MathFunctions : rint(x : double) double
MathFunctions : round(x : double) long
MathFunctions : sin(x : double) double
MathFunctions : sinh(x : double) double
MathFunctions : sqrt(x : double) double
MathFunctions : tan(x : double) double
MathFunctions : tanh(x : double) double
....

==== Requirements
include::../requirements/rc-math-functions.adoc[]

[[rc-arrayrelations]]
=== Requirements Class "Array Relation Functions"
==== Overview

[#img-uml-class-array-relation-functions]
.Array Relation Functions UML Diagram
[plantuml, target=diagram-classes, format=png]
....
interface ArrayRelationFunctions
ArrayRelationFunctions --|> Function : standard functions
ArrayRelationFunctions : a_containedBy(array a, array b) bool
ArrayRelationFunctions : a_contains(array a, array b) bool
ArrayRelationFunctions : a_equals(array a, array b) bool
ArrayRelationFunctions : a_overlaps(array a, array b) bool
ArrayRelationFunctions --> ArrayExpression
....

.Array relation functions
[width="90%",options="header"]
|===
| Name            | Parameters         | Return type  | Definition
| a_containedBy   | (array a, array b) | bool         |
| a_contains      | (array a, array b) | bool         |
| a_equals        | (array a, array b) | bool         |
| a_overlaps      | (array a, array b) | bool         |
|===

==== Requirements

include::../requirements/rc-array-relations.adoc[]

[[rc-textmanipulation]]
=== Requirements Class "Text Manipulation Functions"
==== Overview

[#img-uml-class-text-manipulation-functions]
.Text Manipulation Functions UML Diagram
[plantuml, target=diagram-classes, format=png]
....
interface TextManipulationFunctions
TextManipulationFunctions --|> Function : standard functions
TextManipulationFunctions : caseInsensitize(string s) string
TextManipulationFunctions : accentInsensitize(string s) string
TextManipulationFunctions : lowerCase(string s) string
TextManipulationFunctions : upperCase(string s) string
TextManipulationFunctions : concatenate(string a, string b) string
TextManipulationFunctions : substitute(string s, string a, string b) string
TextManipulationFunctions : format(string f, ...) string
....

.Text manipulation functions
[width="90%",options="header"]
|===
| Name               | Parameters                     | Return type  | Definition
| caseInsensitize    | (string s)                     | string       |
| accentInsensitize  | (string s)                     | string       |
| lowerCase          | (string s)                     | string       |
| upperCase          | (string s)                     | string       |
| concatenate        | (string a, string b)           | string       |
| substitute         | (string s, string a, string b) | string       |
| format             | (string f, ...)                | string       |
|===

==== Requirements

include::../requirements/rc-text-manipulation.adoc[]