== Conformance

The OGC Styles and Symbology Model and Encodings defines multiple requirements classes and their associated conformance classes.

The standardization target for all conformance classes except the conformance classes defining encodings are both Encodings and Rendering engines.
The standardization target for encodings are Rendering Engines and other applications accepting styles as input, as well as applications generating styles (e.g., style editors or converters).

The conformance of all Rendering engines with all conformance classes except the conformance classes defining encodings is with the conceptual model that will result in the expected visual output.
The conformance of all Encodings with the conformance classes targeting them can be either at a conceptual level or at a logical level.
Conformance at the logical level implies conformance at the conceptual level as well.
An Encoding conforms to the logical model if a Style can be encoded using the classes and property names defined in this Standard with only a simple consistent set of rules mapping them to the encoding.
An Encoding can conform to the conceptual model of any conformance class either partially (if it can only preserve some of the information) or fully (if it losslessly preserves all information).

The goal is to allow different encodings to have equivalent content and semantics so that they can be interoperable, by establishing a clear mapping from an encoding
to the logical and/or conceptual model defined in this Standard. The granularity of conformance classes provides a mechanism to clearly indicate which portrayal capabilities
are interoperable with other encodings or rendering engines implementing this Standard.
Most Encodings and Rendering engines are expected to easily conform to the requirements classes for basic portrayal.

This document establishes a core requirements class with a URI of http://www.opengis.net/spec/symbology-1/2.0/req/core.

Requirements and conformance test URIs defined in this document are relative to http://www.opengis.net/spec/symbology-1/2.0.

=== Requirements classes for basic portrayal

*<<rc-core,Requirements Class "Core">>* (http://www.opengis.net/spec/symbology-1/2.0/req/core)

The Core Requirements Class specifies requirements that all encodings and rendering engines must support if claiming conformance with this Standard.
The Core class defines how a Style is defined as a list of StylingRules consisting of a Symbolizer and an optional Selector expression,
as well as a minimal set Symbolizer properties applicable to all types of geospatial data.

*<<rc-vector,Requirements Class "Basic Vector Features Styling">>* (http://www.opengis.net/spec/symbology-1/2.0/req/vector)

The Basic Vector Features Styling Requirements Class specifies requirements for styling vector features data, including referencing feature properties,
specifying a fill and stroke to style vector geometry, as well as defining image, text or dot markers to symbolize points.

*<<rc-coverage,Requirements Class "Basic Coverage Styling">>* (http://www.opengis.net/spec/symbology-1/2.0/req/coverage)

The Basic Coverage Styling Requirements Class specifies requirements for styling coverage data, including referencing coverage range values (e.g., bands),
mapping them to color channels as well as defining colormaps.

*<<rc-labels,Requirements Class "Basic Labeling">>* (http://www.opengis.net/spec/symbology-1/2.0/req/labels)

The Basic Labeling Requirements Class specifies requirements for defining labels to be managed by a placement engine and rendered as a final pass on top of the map.

=== Requirements classes for common portrayal capabilities

*<<rc-hillshading,Requirements Class "Hill Shading">>* (http://www.opengis.net/spec/symbology-1/2.0/req/hillshading)

The Hill Shading Requirements Class specifies requirements for styling elevation coverage data with a hill-shaded style.

*<<rc-fontoutlines,Requirements Class "Font Outlines">>* (http://www.opengis.net/spec/symbology-1/2.0/req/fontoutlines)

The Font Outlines Requirements Class specifies requirements for displaying fonts with outlines so that text can be legible on any background.

*<<rc-hatches,Requirements Class "Hatch Fills">>* (http://www.opengis.net/spec/symbology-1/2.0/req/hatches)

The Hatch Filles Requirements Class specifies requirements for defining fils using hatches

*<<rc-stipples,Requirements Class "Stipple Fills">>* (http://www.opengis.net/spec/symbology-1/2.0/req/stipples)

The Stipple Fills Requirements Class specifies requirements for defining fils using stipples

*<<rc-dashes,Requirements Class "Dashed Stroke">>* (http://www.opengis.net/spec/symbology-1/2.0/req/dashes)

The Dashes Requirements Class specifies requirements for defining dashed strokes.

*<<rc-casing,Requirements Class "Casing and Centerline">>* (http://www.opengis.net/spec/symbology-1/2.0/req/casing)

The Casing and Centerline Requirements Class specifies requirements for defining strokes with built-in casing and centerline.

////
TODO: Clarify how this differs to using a Stroke with a casing on the Shape, and whether this should also be supported for vector geometry?
////

=== Requirements classes for additional expression capabilities

*<<rc-parametervalues,Requirements Class "Parameter Values">>* (http://www.opengis.net/spec/symbology-1/2.0/req/parametervalues)

The Parameter Values Requirements Class specifies requirements for using an Expression to define any property of a Symbolizer.

*<<rc-righthand,Requirements Class "Right-hand Identifiers">>* (http://www.opengis.net/spec/symbology-1/2.0/req/righthand)

The Right-hand Identifiers Requirements Class specifies requirements for defining operation expressions with identifiers on the right-hand side.

*<<rc-conditional,Requirements Class "Conditional Expressions">>* (http://www.opengis.net/spec/symbology-1/2.0/req/conditional)

The Conditional Expressions Requirements Class specifies requirements for defining conditional operation using a ternary `[if] ? [then] : [else]` structure.

*<<rc-variables,Requirements Class "Variables">>* (http://www.opengis.net/spec/symbology-1/2.0/req/variables)

The Variables Requirements Class specifies requirements for defining variables which can be mapped to a dynamic value controlled by an application, or used to facilitate customizing a style.

*<<rc-arithmetic,Requirements Class "Arithmetic Operators">>* (http://www.opengis.net/spec/symbology-1/2.0/req/arithmetic)

The Arithmetic Operators Requirements Class specifies requirements for defining arithmetic operation expressions.

*<<rc-textrelation,Requirements Class "Text Relation Operators">>* (http://www.opengis.net/spec/symbology-1/2.0/req/textrelation)

The Text Relation Operators Requirements Class specifies requirements for defining text relation operation expressions.

*<<rc-functions,Requirements Class "Function Expressions">>* (http://www.opengis.net/spec/symbology-1/2.0/req/functions)

The Functions Requirements Class specifies requirements for defining function call expressions.

**<<rc-math,Requirements Class "Math Functions">>** (http://www.opengis.net/spec/symbology-1/2.0/conf/rc-math)

The Math Functions Requirements Class specifies requirements for defining math functions to be used with numeric properties.

*<<rc-arrayrelations,Requirements Class "Array Relation Functions">>* (http://www.opengis.net/spec/symbology-1/2.0/req/arrayrelations)

The Array Relation Requirements Class specifies requirements for standardized array relation functions to be used with array properties.

*<<rc-textmanipulation,Requirements Class "Text Manipulation Functions">>* (http://www.opengis.net/spec/symbology-1/2.0/req/textmanipulation)

The Text Manipulation Requirements Class specifies requirements for standardized text manipulation functions to be used with text properties.

=== Requirements classes defining encodings

*<<rc-json,Requirements Class "JSON Styles and Symbology">>* (http://www.opengis.net/spec/symbology-1/2.0/req/json)

*<<rc-cscss,Requirements Class "Cartographic Symbology Cascading Style Sheets">>* (http://www.opengis.net/spec/symbology-1/2.0/req/cscss)

=== Declaration of conformance

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document conformance to the respective conformance class is declared using the URIs listed
in <<table_conformance_urls>>. A rendering engine accessible as an Web API can declare conformance to this Standard in its Conformance Declaration response.

The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the
OGC Compliance Testing Policies and Procedures (https://docs.ogc.org/pol/08-134r11.html[OGC 08-134r11]) and the https://www.ogc.org/compliance[OGC Compliance Testing website].

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

Full conformance at the conceptual level but not at the logical level, which can losslessly preserve all information of the conceptual model defined in a particular requirements class
but necessitates defining a custom mapping and cannot be automated from a simple consistent set of encoding rules, is declared by appending `-concept` to the conformance URI.

Partial conformance at the conceptual level which can preserve some but not all information of the conceptual model defined in a particular requirements class
is declared by appending `-partial-concept` to the conformance URI.

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Conformance class                                               |URI
|<<rc-core,Core>>                                                 |http://www.opengis.net/spec/symbology-1/2.0/conf/core
|<<rc-vector,Basic Vector Features Styling>>                      |http://www.opengis.net/spec/symbology-1/2.0/conf/vector
|<<rc-coverage,Basic Coverage Styling>>                           |http://www.opengis.net/spec/symbology-1/2.0/conf/coverage
|<<rc-labels,Basic Labeling>>                                     |http://www.opengis.net/spec/symbology-1/2.0/conf/labels
|<<rc-hillshading,Hill Shading>>                                  |http://www.opengis.net/spec/symbology-1/2.0/conf/hillshading
|<<rc-fontoutlines,Font Outlines>>                                |http://www.opengis.net/spec/symbology-1/2.0/conf/fontoutlines
|<<rc-hatches,Hatch Fills>>                                       |http://www.opengis.net/spec/symbology-1/2.0/conf/hatches
|<<rc-stipples, Stipple Fills>>                                   |http://www.opengis.net/spec/symbology-1/2.0/conf/stipples
|<<rc-dashes,Dashed Strokes>>                                     |http://www.opengis.net/spec/symbology-1/2.0/conf/dashes
|<<rc-casing,Casing and Centerline>>                              |http://www.opengis.net/spec/symbology-1/2.0/conf/casing
|<<rc-parametervalues,Parameter Values>>                          |http://www.opengis.net/spec/symbology-1/2.0/conf/parametervalues
|<<rc-functions,Function Expressions>>                            |http://www.opengis.net/spec/symbology-1/2.0/conf/functions
|<<rc-math,Math Functions>>                                       |http://www.opengis.net/spec/symbology-1/2.0/conf/math
|<<rc-arrayrelations,Array Relation Functions>>                   |http://www.opengis.net/spec/symbology-1/2.0/conf/arrayrelations
|<<rc-textmanipulation,Text Manipulation Functions>>              |http://www.opengis.net/spec/symbology-1/2.0/conf/textmanipulation
|<<rc-arithmetic,Arithmetic Operators>>                           |http://www.opengis.net/spec/symbology-1/2.0/conf/arithmetic
|<<rc-textrelation,Text Relation Operators>>                      |http://www.opengis.net/spec/symbology-1/2.0/conf/textrelation
|<<rc-righthand,Any right-hand operands>>                         |http://www.opengis.net/spec/symbology-1/2.0/conf/righthand
|<<rc-conditional,Conditional Expressions>>                       |http://www.opengis.net/spec/symbology-1/2.0/conf/conditional
|<<rc-variables,Variables>>                                       |http://www.opengis.net/spec/symbology-1/2.0/conf/variables
|<<rc-json,JSON Styles and Symbology>>                            |http://www.opengis.net/spec/symbology-1/2.0/conf/json
|<<rc-cscss,Cartographic Symbology Cascading Style Sheets>>       |http://www.opengis.net/spec/symbology-1/2.0/conf/cscss
|===
