== Conformance

The OGC Cartographic Symbology - Part 3 - Model extension for geometry relations and manipulation defines multiple requirements classes and their associated conformance classes, extending the core model
defined in Part 1. The encodings defined in Part 1 can be also used to encode the capabilities defined in this extension.

The standardization target for all conformance classes are both Encodings and Rendering engines.

The conformance of all Rendering engines with all conformance classes is with the conceptual model that will result in the expected visual output.
Conformance at the logical level implies conformance at the conceptual level as well.
An Encoding conforms to the logical model if a Style can be encoded using the classes and property names defined in this Standard with only a simple consistent set of rules mapping them to the encoding.
An Encoding can conform to the conceptual model of any conformance class either partially (if it can only preserve some of the information) or fully (if it losslessly preserves all information).

The goal is to allow different encodings to have equivalent content and semantics so that they can be interoperable, by establishing a clear mapping from an encoding
to the logical and/or conceptual model defined in this Standard. The granularity of conformance classes provides a mechanism to clearly indicate which portrayal capabilities
are interoperable with other encodings or rendering engines implementing this Standard.
Most Encodings and Rendering engines are expected to easily conform to the requirements classes for basic portrayal.

Requirements and conformance test URIs defined in this document are relative to http://www.opengis.net/spec/symbology-3/1.0.

=== Requirements classes for geometry relation and manipulation capabilities

*<<rc-symbolizer-geometry,Requirements Class "Symbolizer Geometry Selection">>* (http://www.opengis.net/spec/symbology-3/1.0/req/symbolizergeometry)

The Symbolizer Geometry Selection Requirements Class specifies requirements for specifying which geometry to render.

*<<rc-spatial,Requirements Class "Spatial Relation Functions">>* (http://www.opengis.net/spec/symbology-3/1.0/req/spatial)

The Spatial Relation Requirements Class specifies requirements for standardized spatial relation functions to be used with feature geometry.

*<<rc-temporal,Requirements Class "Temporal Relation Functions">>* (http://www.opengis.net/spec/symbology-3/1.0/req/temporal)

The Temporal Relation Requirements Class specifies requirements for standardized temporal relation functions to be used with temporal properties.

*<<rc-geometrymanipulation,Requirements Class "Geometry Manipulation Functions">>* (http://www.opengis.net/spec/symbology-3/1.0/req/geometrymanipulation)

The Geometry Manipulation Requirements Class specifies requirements for standardized geometry manipulation functions to be used with feature geometry.

=== Declaration of conformance

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document conformance to the respective conformance class is declared using the URIs listed
in <<table_conformance_urls>>. A rendering engine accessible as an Web API can declare conformance to this Standard in its Conformance Declaration response.

The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the
OGC Compliance Testing Policies and Procedures (https://docs.ogc.org/pol/08-134r11.html[OGC 08-134r11]) and the https://www.ogc.org/compliance[OGC Compliance Testing website].

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

Full conformance at the conceptual level but not at the logical level, which can losslessly preserve all information of the conceptual model defined in a particular requirements class
but necessitates defining a custom mapping and cannot be automated from a simple consistent set of encoding rules, is declared by appending `-concept` to the conformance URI.

Partial conformance at the conceptual level which can preserve some but not all information of the conceptual model defined in a particular requirements class
is declared by appending `-partial-concept` to the conformance URI.

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Conformance class                                               |URI
|<<rc-symbolizer-geometry,Symbolizer Geometry Selection>>         |http://www.opengis.net/spec/symbology-3/1.0/conf/symbolizergeometry
|<<rc-spatial,Spatial Relation Functions>>                        |http://www.opengis.net/spec/symbology-3/1.0/conf/spatial
|<<rc-temporal,Temporal Relation Functions>>                      |http://www.opengis.net/spec/symbology-3/1.0/conf/temporal
|<<rc-geometry-manipulation,Geometry Manipulation Functions>>      |http://www.opengis.net/spec/symbology-3/1.0/conf/geometrymanipulation
|===
